folio-org/mod-fqm-manager

- src/main/resources/db/changelog/changes/v1.0.0/entity-type-definitions.xml
- src/main/resources/db/changelog/changes/v1.0.0/harvested-views.xml
- src/main/resources/db/changelog/changes/v1.0.0/sql/derived-tables/create-view-user-details.sql
- src/main/resources/db/changelog/changes/v1.0.0/sql/entity-type-definitions/insert-user-addresstype-definitions.sql
- src/main/resources/db/changelog/changes/v1.0.0/sql/entity-type-definitions/insert-user-details-definition.sql
https://issues.folio.org/browse/MODFQMMGR-6
Support reporting on User's Addresses
If we change the primary address of user then it changes here as well
> MODFQMMGR-6:Support reporting on User Addresses

- src/main/resources/db/changelog/changes/v1.0.0/sql/derived-tables/create-view-user-details.sql
- src/main/resources/db/changelog/changes/v1.0.0/sql/entity-type-definitions/insert-user-details-definition.sql
https://issues.folio.org/browse/MODFQMMGR-17
> MODFQMMGR-17:Sort the column of user entity type alphabetically

- src/test/java/org/folio/fqm/ModFqmManagerIT.java
https://issues.folio.org/browse/MODFQMMGR-19
> MODFQMMGR-19:Fix the new integration test timeout issue

- README.md
This adds the required license information, link to issue tracker, and additional information to the README. These are all based on mod-settings README
> MODFQMMGR-4 Add required sections to the readme

- src/main/resources/db/changelog/changes/v1.0.0/sql/derived-tables/create-view-item-details.sql
- src/main/resources/db/changelog/changes/v1.0.0/sql/entity-type-definitions/insert-item-details-definition.sql
https://issues.folio.org/browse/MODFQMMGR-8
> MODFQMMGR-8:Investigate data discrepancy

- src/main/resources/db/changelog/changes/v1.0.0/sql/create-derived-table-definition.sql
- src/main/resources/db/changelog/changes/v1.0.0/sql/create-query-details-table.sql
- src/main/resources/db/changelog/changes/v1.0.0/sql/create-query-results-table.sql
https://issues.folio.org/browse/MODFQMMGR-33
> MODFQMMGR-33-sorting the deployment issue

- src/main/resources/db/changelog/changes/v1.0.0/harvested-views.xml
- src/main/resources/db/changelog/changes/v1.0.0/sql/derived-tables/create-view-circulation-loan-status.sql
- src/main/resources/db/changelog/changes/v1.0.0/sql/derived-tables/create-view-inventory-item-status.sql
https://issues.folio.org/browse/MODFQMMGR-33
> MODFQMMGR-33:sorting the deployment issue

- src/main/resources/db/changelog/changes/v1.0.0/sql/entity-type-definitions/insert-item-details-definition.sql
https://issues.folio.org/browse/MODFQMMGR-44
> MODFQMMGR-44:removing item effective call number

- src/main/resources/db/changelog/changes/v1.0.0/sql/derived-tables/create-view-user-details.sql
- src/main/resources/db/changelog/changes/v1.0.0/sql/entity-type-definitions/insert-user-details-definition.sql
https://issues.folio.org/browse/MODFQMMGR-34
> MODFQMMGR-34:user record type should be prepended in the Query

- src/main/resources/db/changelog/changes/v1.0.0/sql/create-query-details-table.sql
https://issues.folio.org/browse/MODFQMMGR-35
> MODFQMMGR-35: Error 400 when trying to test query

- src/main/resources/db/changelog/changes/v1.0.0/sql/derived-tables/create-view-user-details.sql
https://issues.folio.org/browse/MODFQMMGR-32
> MODFQMMGR-32:primary address fields not ordered

- src/main/resources/db/changelog/changes/v1.0.0/entity-type-definitions.xml
> MODFQMMGR-47: Improve performance of instance title search in Items entity type

- src/main/resources/db/changelog/changes/v1.0.1/drv_item_callnumber_location_create.xml
https://issues.folio.org/browse/MODFQMMGR-49
> fixing effective call number

- src/main/resources/application.yml
This just re-introduces the changes that were accidentally merged before they'd be reviewed
> MODFQMMGR-67 Enable batched inserts

- src/main/resources/db/changelog/changes/v1.0.1/update_users_entity_type_definition.sql
https://issues.folio.org/browse/MODFQMMGR-31
> fixing users dropdown

- src/main/resources/db/changelog/changes/v1.0.2/remove_items_holdingsrecord_instance_title_searchable.xml
Fix view name in liquibase 1.0.2 scripts
> Fix view name in liquibase 1.0.2 scripts

- src/main/resources/db/changelog/changes/v1.0.2/changelog-v1.0.2.xml
- src/main/resources/db/changelog/changes/v1.0.2/fix_user_details_preferred_contact_type.xml
- src/main/resources/db/changelog/changes/v1.0.2/update_user_details_entity_type_definition.xml
https://issues.folio.org/browse/MODFQMMGR-75
> User preferred contact type is incorrect in the records table

- src/main/resources/db/changelog/changes/v1.0.3/changelog-v1.0.3.xml
- src/main/resources/db/changelog/changes/v1.0.3/sql/refactor drv_item_callnumber_location.xml
https://issues.folio.org/browse/MODFQMMGR-58
> refactor drv item call number view

- pom.xml
https://issues.folio.org/browse/MODFQMMGR-91
> MODFQMMGR-91: changing version in pom file

- src/main/resources/db/changelog/changes/v1.0.4/sql/entity-type-definitions/insert-purchase-order-line-definition.sql
- translations/mod-fqm-manager/en.json
https://issues.folio.org/browse/MODFQMMGR-91
> MODFQMMGR-91:fixing typos

- README.md
- src/main/java/org/folio/fqm/service/ResultSetService.java
- src/test/java/org/folio/fqm/service/ResultSetServiceTest.java
[MODFQMMGR-125](https://issues.folio.org/browse/MODFQMMGR-125)
> MODFQMMGR-125: Add _deleted field for content items that have been deleted

- src/main/java/org/folio/fqm/service/FqlToSqlConverterService.java
- src/test/java/org/folio/fqm/service/FqlToSqlConverterServiceTest.java
[MODFQMMGR-119](https://issues.folio.org/browse/MODFQMMGR-119): Create new operators to support searching for null/empty values
> MODFQMMGR-119: Add empty FQL operator

- src/main/resources/db/changelog/changes/v1.1.0/update-drv-purchase-order-line-details-definition.xml
- src/main/resources/db/changelog/changes/v1.1.0/update-drv-user-details-definition.xml
Remove value functions from array types
> Remove value functions from array types

- src/main/java/org/folio/fqm/repository/EntityTypeRepository.java
- src/main/java/org/folio/fqm/service/EntityTypeService.java
- src/main/resources/db/changelog/changes/v1.1.0/changelog-v1.1.0.xml
- src/main/resources/db/changelog/changes/v1.1.0/harvested-views.xml
- src/main/resources/db/changelog/changes/v1.1.0/sql/entity-type-definitions/insert-custom-fields-definition.sql
- src/test/java/org/folio/fqm/repository/EntityTypeRepositoryTest.java
- src/test/resources/test-db/scripts/custom-fields-entity-type-definition.sql
- src/test/resources/test-db/scripts/custom-fields-source-view.sql
- src/test/resources/test-db/scripts/entity_type-02-definition.sql
- src/test/resources/test-db/test-entity-type-definitions.xml
>  kriti/MODFQMMGR-99: adding user custom fields

- src/main/java/org/folio/fqm/repository/EntityTypeRepository.java
- src/main/resources/db/changelog/changes/v1.1.0/sql/entity-type-definitions/insert-custom-fields-definition.sql
- src/test/resources/test-db/scripts/custom-fields-entity-type-definition.sql
- translations/mod-fqm-manager/en_US.json
> MODFQMMGR-155: handle custom fields across all modules

- .gitignore
- src/main/resources/db/changelog/changes/v1.1.0/update-drv-purchase-order-line-details-definition.xml
Oops. `dataType` requires a nested object with a `dataType` field inside it, rather than just a plain string.
> [MODFQMMGR-150] Properly serialize nested data types

- src/main/java/org/folio/fqm/service/FqlToSqlConverterService.java
Change the existing `Map` to a basic switch-case with explicit casts.
> [MODFQMMGR-165] Refactor FqlToSqlConverterService condition mapping

- src/main/resources/db/changelog/changes/v1.1.0/update-drv-purchase-order-line-details-definition.xml
Add value function to numberType columns so that they can be queried correctly.
> Add value function to numberType columns

- src/main/java/org/folio/fqm/repository/EntityTypeRepository.java
Add datatype string to custom field columns so that they work again.
> Add datatype string to boolean custom fields

- src/main/resources/db/changelog/changes/v1.1.0/changelog-v1.1.0.xml
- src/main/resources/db/changelog/changes/v1.1.0/insert-instances-definition.xml
- translations/mod-fqm-manager/en.json
This commit adds the Instances entity type, containing a subset of the fields it will eventually have
> MODFQMMGR-129 Add Instances entity type

- src/main/resources/db/changelog/changes/v1.1.0/update-drv-purchase-order-line-details-definition.xml
[MODFQMMGR-167](https://folio-org.atlassian.net/browse/MODFQMMGR-167): Fix a few fields that can't be queried
> MODFQMMGR-167: Fix fields that cannot be queried

- src/main/java/org/folio/fqm/service/FqlToSqlConverterService.java
- src/main/resources/db/changelog/changes/v1.1.0/sql/entity-type-definitions/insert-holdings-definition.sql
- src/main/resources/db/changelog/changes/v1.1.0/update-drv-purchase-order-line-details-definition.xml
- src/main/resources/db/changelog/changes/v1.1.0/update-drv-user-details-definition.xml
- src/test/java/org/folio/fqm/service/FqlToSqlConverterServiceTest.java
- translations/mod-fqm-manager/en.json
[MODFQMMGR-131](https://folio-org.atlassian.net/browse/MODFQMMGR-131): Add contains_all and not_contains_all operators
> MODFQMMGR-131: Add contains_all and not_contains_all operators

- src/main/java/org/folio/fqm/repository/QueryRepository.java
- src/main/java/org/folio/fqm/repository/ResultSetRepository.java
- src/main/java/org/folio/fqm/service/QueryManagementService.java
- src/test/java/org/folio/fqm/service/QueryManagementServiceTest.java
Address [MODFQMMGR-183](https://folio-org.atlassian.net/browse/MODFQMMGR-183) by ensuring that id columns are always added to a query's fields.
> MODFQMMGR-183: Add all id columns to query fields

- src/main/java/org/folio/fqm/service/FqlToSqlConverterService.java
- src/test/java/org/folio/fqm/service/FqlToSqlConverterServiceTest.java
[MODFQMMGR-130](https://folio-org.atlassian.net/browse/MODFQMMGR-130): Add contains_any and not_contains_any operators
> MODFQMMGR-130: Add contains_any and not_contains_any FQL operators

- src/main/java/org/folio/fqm/repository/MaterializedViewRefreshRepository.java
- src/main/resources/db/changelog/changes/v1.1.0/changelog-v1.1.0.xml
- src/main/resources/db/changelog/changes/v1.1.0/insert-instances-definition.xml
- src/main/resources/db/changelog/changes/v1.1.0/sql/create-mat-view-languages.sql
- src/main/resources/db/changelog/changes/v1.1.0/sql/entity-type-definitions/insert-languages-definition.sql
Adding drop down on languages field in instance entity type
> MODFQMMGR-171-dropdown-lang: create drop down for lang in instance entity type

- src/main/resources/db/changelog/changes/v1.1.0/sql/entity-type-definitions/insert-purchase-order-line-definition.sql
- src/main/resources/db/changelog/changes/v1.1.0/update-drv-purchase-order-line-details-definition.xml
- src/main/resources/db/changelog/changes/v1.1.0/update-drv-user-details-definition.xml
forgot these the first time :(
> [MODFQMMGR-191] Add remaining queryable=false

- src/main/java/org/folio/fqm/service/QueryManagementService.java
- src/test/java/org/folio/fqm/service/QueryManagementServiceTest.java
Ensure id columns are always included in query contents. This change is needed to make sure the GET /query/contents API works whether the fields parameter:
- is not included
- is included
- is included, but is missing id columns
> Ensure id columns are always included in query contents

- src/main/resources/db/changelog/changes/v1.1.0/insert-instances-definition.xml
> [MODFQMMGR-200] Revert over-eager setting queryable=false for instance statuses

- src/main/resources/db/changelog/changes/v1.1.0/update-drv-user-details-definition.xml
> MODFQMMGR-206: setting true to barcode

- src/main/java/org/folio/fqm/service/EntityTypeService.java
- src/main/resources/db/changelog/changes/v1.1.0/update-drv-purchase-order-line-details-definition.xml
Sort currencies alphabetically in dropdown menu.
> Sort currencies alphabetically

- src/main/java/org/folio/fqm/service/FqlToSqlConverterService.java
- src/test/java/org/folio/fqm/service/FqlToSqlConverterServiceTest.java
[MODFQMMGR-207: null/empty operator doesn't work with several fields](https://folio-org.atlassian.net/browse/MODFQMMGR-207)
> MODFQMMGR-207: null/empty operator doesn't work with several fields

- descriptors/ModuleDescriptor-template.json
> MODFQMMGR-214: adding dependencies

- src/main/resources/db/changelog/changelog-master.xml
- src/main/resources/db/changelog/changes/v1.2.0/changelog-v1.2.0.xml
- src/main/resources/db/changelog/changes/v1.2.0/update-drv-item-details-definition.xml
- src/main/resources/db/changelog/changes/v1.2.0/update-drv-loan-details-definition.xml
- src/main/resources/db/changelog/changes/v1.2.0/update-drv-user-details-definition.xml
> MODFQMMGR-161:Populate existing column values from APIs

- src/main/resources/db/changelog/changes/v1.2.0/update-drv-user-details-definition.xml
> MODFQMMGR-162:adding value source api

- src/main/java/org/folio/fqm/config/DataSourceConfiguration.java
- src/main/java/org/folio/fqm/repository/EntityTypeRepository.java
- src/main/java/org/folio/fqm/repository/IdStreamer.java
- src/main/java/org/folio/fqm/repository/QueryResultsRepository.java
- src/main/java/org/folio/fqm/repository/ResultSetRepository.java
This commit fixes a bug where Spring wasn't properly configured to ever use the read replica. It also fixes some minor sonar warnings related to Spring dependency injection
> MODFQMMGR-217 Fix read/write split bug

- translations/mod-fqm-manager/ar.json
- translations/mod-fqm-manager/ber.json
- translations/mod-fqm-manager/ca.json
- translations/mod-fqm-manager/da.json
- translations/mod-fqm-manager/de.json
- translations/mod-fqm-manager/en.json
- translations/mod-fqm-manager/en_GB.json
- translations/mod-fqm-manager/en_SE.json
- translations/mod-fqm-manager/en_US.json
- translations/mod-fqm-manager/es.json
- translations/mod-fqm-manager/es_419.json
- translations/mod-fqm-manager/es_ES.json
- translations/mod-fqm-manager/fr.json
- translations/mod-fqm-manager/fr_FR.json
- translations/mod-fqm-manager/he.json
- translations/mod-fqm-manager/hi_IN.json
- translations/mod-fqm-manager/hu.json
- translations/mod-fqm-manager/it_IT.json
- translations/mod-fqm-manager/ja.json
- translations/mod-fqm-manager/ko.json
- translations/mod-fqm-manager/nb.json
- translations/mod-fqm-manager/nn.json
- translations/mod-fqm-manager/pl.json
- translations/mod-fqm-manager/pt_PT.json
- translations/mod-fqm-manager/ru.json
- translations/mod-fqm-manager/sk.json
- translations/mod-fqm-manager/sv.json
- translations/mod-fqm-manager/ur.json
- translations/mod-fqm-manager/zh_CN.json
Minor fix (more to come for this same Jira ticket), but will fix observed "incorrect" sorting in the instances "show columns" dropdown
> [MODFQMMGR-88] Fix typo in instance statistical code list field name

- src/main/java/org/folio/fqm/repository/DataRefreshRepository.java
> Add Euro currency support

- src/main/java/org/folio/fqm/repository/EntityTypeRepository.java
- src/test/java/org/folio/fqm/repository/ResultSetRepositoryArrayTest.java
- src/test/java/org/folio/fqm/repository/ResultSetRepositoryTest.java
- src/test/java/org/folio/fqm/utils/IdStreamerTest.java
Add writer jooq context to EntityTypeRepository to allow definitions to be updated
> Add writer context to EntityTypeRepository

- descriptors/ModuleDescriptor-template.json
- src/main/resources/db/changelog/changes/v1.1.0/harvested-views.xml
> MODFQMMGR-258: Add src_organization_categories view

- src/main/java/org/folio/fqm/repository/EntityTypeRepository.java
This commit changes the entity type initialization process, so that only the entity types that are defined in JSON files are replaced. Any that are in the DB, but aren't defined in JSON files, will be left untouched. This prevents a non-deterministic test failure (in FqlToSqlConverterServiceIT) and also allows for custom entity types
> MODFQMMGR-267 Only replace defined entity types when initializing

- entity-type-creator/components/EntityTypeFieldEditor.tsx
- entity-type-creator/components/JSONTable.tsx
- entity-type-creator/components/ModuleInstaller.tsx
- entity-type-creator/components/PostgresConnector.tsx
- entity-type-creator/components/QueryTool.tsx
- entity-type-creator/pages/api/socket.ts
- entity-type-creator/pages/index.tsx
- entity-type-creator/socket/fqm.ts
entity type creator changes from #240, for master
> Entity type creator fixes

- src/main/resources/entity-types/inventory/drv_locations.json5
- translations/mod-fqm-manager/en.json
> Modfqmmgr 236

- src/main/resources/db/changelog/changes/v2.1.0/changelog-v2.1.0.xml
- src/main/resources/entity-types/configuration/drv_config_data_details.json5
- translations/mod-fqm-manager/en.json
> Modfqmmgr 237

- src/main/resources/entity-types/users/drv_simple_user_details.json5
> Trying to fix the simple user entity type

- translations/mod-fqm-manager/en.json
> Fixing translatn

- entity-type-creator/components/EntityTypeFieldEditor.tsx
- entity-type-creator/components/NewEntityTypeDialog.tsx
sometimes, choosing something from the dropdown would cause the value to not actually get set internally, despite it looking like it worked in the UI :(
> minor entity type creator fix

- entity-type-creator/components/EntityTypeFieldEditor.tsx
- entity-type-creator/components/NewEntityTypeDialog.tsx
- entity-type-creator/components/SourceEditor.tsx
Sometimes, picking items from a dropdown would cause them to not actually get set, despite it looking fine, leading to some very frustrating errors :(
> Assorted entity type creator fixes

- src/main/resources/entity-types/circulation/drv_loan_details.json5
- src/main/resources/entity-types/inventory/drv_holdings_record_details.json5
- src/main/resources/entity-types/inventory/drv_instances.json5
- src/main/resources/entity-types/inventory/drv_item_details.json5
- src/main/resources/entity-types/organizations/drv_organization_contacts.json5
- src/main/resources/entity-types/organizations/drv_organization_details.json5
- src/main/resources/entity-types/users/drv_user_details.json5
- src/test/java/org/folio/fqm/IntegrationTestBase.java
Add entity type permissions
https://folio-org.atlassian.net/browse/MODFQMMGR-298 
https://folio-org.atlassian.net/browse/MODFQMMGR-301
https://folio-org.atlassian.net/browse/MODFQMMGR-297
https://folio-org.atlassian.net/browse/MODFQMMGR-300
https://folio-org.atlassian.net/browse/MODFQMMGR-299
https://folio-org.atlassian.net/browse/MODFQMMGR-265
https://folio-org.atlassian.net/browse/MODFQMMGR-296
> Add entity type permissions

- README.md
Added an explanation detailing the exact resource allocation for the module.
> MODFQMMGR-222

- src/main/java/org/folio/fqm/aspect/EntityTypePermissionsAspect.java
> [MODFQMMGR-325] Resolve race condition in permission logic

- src/main/resources/entity-types/inventory/simple_holdings_records.json5
> fixing-value-getter: fixing the brackets

- src/main/java/org/folio/fqm/repository/DataRefreshRepository.java
- src/main/java/org/folio/fqm/resource/DataRefreshController.java
- src/main/java/org/folio/fqm/service/DataRefreshService.java
- src/main/resources/swagger.api/mod-fqm-manager.yaml
- src/test/java/org/folio/fqm/controller/DataRefreshControllerTest.java
- src/test/java/org/folio/fqm/repository/DataRefreshRepositoryTest.java
- src/test/java/org/folio/fqm/service/DataRefreshServiceTest.java
[MODFQMMGR-331: Retry materialized view refresh on failure](https://folio-org.atlassian.net/browse/MODFQMMGR-331)
> MODFQMMGR-331: Retry materialized view refresh on failure

- src/main/resources/entity-types/inventory/simple_holdings_records.json5
> [MODFQMMGR-344] Make holdings.receiving_history_display_type queryable

- src/main/resources/entity-types/circulation/simple_loan.json5
- src/main/resources/entity-types/users/simple_user_details.json5
> MODFQMMGR-336: measure performance of composite entity type

- src/main/java/org/folio/fqm/service/MigrationService.java
> [MODFQMMGR-389] Migration service interface

- src/main/java/org/folio/fqm/service/EntityTypeService.java
- src/test/java/org/folio/fqm/service/EntityTypeServiceTest.java
Remove duplicates when returning pre-defined field values
> Remove duplicates when returning pre-defined field values

- src/main/java/org/folio/fqm/resource/EntityTypeController.java
- src/main/java/org/folio/fqm/service/EntityTypeService.java
- src/main/java/org/folio/fqm/service/QueryManagementService.java
- src/main/resources/entity-types/circulation/simple_loan.json5
- src/main/resources/entity-types/circulation/simple_loan_policy.json5
- src/main/resources/entity-types/inventory/simple_call_number_type.json5
- src/main/resources/entity-types/inventory/simple_holdings_records.json5
- src/main/resources/entity-types/inventory/simple_instance.json5
- src/main/resources/entity-types/inventory/simple_instance_status.json5
- src/main/resources/entity-types/inventory/simple_instance_type.json5
- src/main/resources/entity-types/inventory/simple_item_details.json5
- src/main/resources/entity-types/inventory/simple_loan_types.json5
- src/main/resources/entity-types/inventory/simple_locations.json5
- src/main/resources/entity-types/inventory/simple_loclibrary.json5
- src/main/resources/entity-types/inventory/simple_material_type_details.json5
- src/main/resources/entity-types/inventory/simple_service_point_details.json5
- src/main/resources/entity-types/inventory/simple_statistical_code.json5
- src/main/resources/entity-types/inventory/simple_statistical_code_type.json5
- src/main/resources/entity-types/orders/simple_purchase_order.json5
- src/main/resources/entity-types/orders/simple_purchase_order_line.json5
- src/main/resources/entity-types/organizations/simple_organization_types.json5
- src/main/resources/entity-types/organizations/simple_organizations.json5
- src/main/resources/entity-types/users/simple_group_details.json5
- src/main/resources/entity-types/users/simple_user_details.json5
- src/test/java/org/folio/fqm/controller/EntityTypeControllerTest.java
- src/test/java/org/folio/fqm/service/EntityTypeServiceTest.java
- src/test/java/org/folio/fqm/service/QueryManagementServiceTest.java
> MODFQMMGR-390-hidden-col: hiding col in UI

- src/main/resources/application.yml
> Set debug to false

- src/main/resources/entity-types/inventory/composite_instances.json5
- src/main/resources/entity-types/inventory/simple_instance.json5
- src/main/resources/entity-types/inventory/simple_instance_status.json5
> fixing instance status

- src/main/java/org/folio/fqm/repository/IdStreamer.java
- src/main/java/org/folio/fqm/repository/ResultSetRepository.java
- src/main/java/org/folio/fqm/service/CrossTenantQueryService.java
- src/main/java/org/folio/fqm/service/EntityTypeFlatteningService.java
- src/main/java/org/folio/fqm/service/EntityTypeService.java
- src/main/java/org/folio/fqm/service/QueryManagementService.java
- src/main/java/org/folio/fqm/service/QueryProcessorService.java
- src/main/resources/entity-types/inventory/composite_instances.json5
- src/test/java/org/folio/fqm/repository/ResultSetRepositoryTest.java
- src/test/java/org/folio/fqm/repository/ResultSetRepositoryTestDataProvider.java
- src/test/java/org/folio/fqm/service/CrossTenantQueryServiceTest.java
- src/test/java/org/folio/fqm/service/EntityTypeServiceTest.java
- src/test/java/org/folio/fqm/service/QueryManagementServiceTest.java
- src/test/java/org/folio/fqm/service/QueryProcessorServiceTest.java
- src/test/java/org/folio/fqm/utils/IdStreamerTest.java
- src/test/java/org/folio/fqm/utils/IdStreamerTestDataProvider.java
[MODFQMMGR-424](https://folio-org.atlassian.net/browse/MODFQMMGR-424): Remove shadow instances from results
> MODFQMMGR-424: Remove shadow instances from results

- src/main/resources/entity-types/inventory/simple_instance_status.json5
Reverts folio-org/mod-fqm-manager#371
> Revert "fixing instance status"

- src/main/java/org/folio/fqm/repository/EntityTypeRepository.java
- src/main/java/org/folio/fqm/service/CrossTenantQueryService.java
- src/test/java/org/folio/fqm/repository/EntityTypeRepositoryTest.java
- src/test/java/org/folio/fqm/service/CrossTenantQueryServiceTest.java
- src/test/java/org/folio/fqm/utils/IdStreamerTest.java
[MODFQMMGR-425](https://folio-org.atlassian.net/browse/MODFQMMGR-425): Retrieve shared instances when in a member tenant
> MODFQMMGR-425: Retrieve shared instances when in a member tenant

- src/main/resources/db/changelog/changes/v2.1.0/changelog-v2.1.0.xml
- src/main/resources/entity-types/inventory/simple_instance.json5
- translations/mod-fqm-manager/en.json
- translations/mod-fqm-manager/en_US.json
> MODFQMMGR-332:adding instance-format

- src/main/java/org/folio/fqm/service/EntityTypeService.java
- src/main/resources/entity-types/inventory/composite_holdings_record.json5
- src/test/java/org/folio/fqm/service/EntityTypeServiceTest.java
[MODFQMMGR-433](https://folio-org.atlassian.net/browse/MODFQMMGR-433): Query holdings of shared instances from Central tenant
> MODFQMMGR-433: Enable cross-tenant queries for Holdings entity type

- src/main/java/org/folio/fqm/service/EntityTypeService.java
- src/main/resources/entity-types/inventory/simple_instance.json5
> sorting valueApi stuff plus remove status Id column for instance

- src/main/resources/entity-types/inventory/simple_instance.json5
> [MODFQMMGR-249] Hide instance_type_id field

- src/main/resources/entity-types/inventory/composite_item_details.json5
[MODFQMMGR-449](https://folio-org.atlassian.net/browse/MODFQMMGR-449)
[MODFQMMGR-450](https://folio-org.atlassian.net/browse/MODFQMMGR-450)
[MODFQMMGR-451](https://folio-org.atlassian.net/browse/MODFQMMGR-451)
> MODFQMMGR-449: Enable cross-tenant queries for items

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/fqm/service/CrossTenantQueryService.java
- src/main/java/org/folio/fqm/service/EntityTypeFlatteningService.java
- src/main/java/org/folio/fqm/service/EntityTypeInitializationService.java
- src/test/java/org/folio/fqm/IntegrationTestBase.java
- src/test/java/org/folio/fqm/context/TestDbSetupConfiguration.java
- src/test/java/org/folio/fqm/repository/QueryResultsRepositoryTest.java
- src/test/java/org/folio/fqm/service/CrossTenantQueryServiceTest.java
- src/test/java/org/folio/fqm/service/EntityTypeFlatteningServiceTest.java
- src/test/java/org/folio/fqm/utils/IdStreamerTest.java
This reverts commit ada92843f0f115c43f875ae7da07b51ef23c0298.
> Revert "MODFQMMGR-462 Get tenant data from user-tenants"

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/fqm/service/CrossTenantQueryService.java
- src/main/java/org/folio/fqm/service/EntityTypeFlatteningService.java
- src/main/java/org/folio/fqm/service/EntityTypeInitializationService.java
- src/test/java/org/folio/fqm/IntegrationTestBase.java
- src/test/java/org/folio/fqm/context/TestDbSetupConfiguration.java
- src/test/java/org/folio/fqm/repository/QueryResultsRepositoryTest.java
- src/test/java/org/folio/fqm/service/CrossTenantQueryServiceTest.java
- src/test/java/org/folio/fqm/service/EntityTypeFlatteningServiceTest.java
- src/test/java/org/folio/fqm/utils/IdStreamerTest.java
This reverts commit ada4908 and adds missing required permissions to the tenant management API
> Revert "Revert "MODFQMMGR-462 Get tenant data from user-tenants""

- src/main/java/org/folio/fqm/service/CrossTenantQueryService.java
> MODFQMMGR-462 Fix NPE

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/fqm/resource/MigrationController.java
- src/main/resources/swagger.api/mod-fqm-manager.yaml
- src/main/resources/swagger.api/schemas/FqmMigrateRequest.json
- src/main/resources/swagger.api/schemas/FqmMigrateResponse.json
- src/test/java/org/folio/fqm/controller/MigrationControllerTest.java
> Adding an end point /fqm/migrate

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/fqm/service/CrossTenantQueryService.java
> MODFQMMGR-462 Add a missing module permission + logging

- src/main/resources/entity-types/inventory/simple_instance.json5
[MODFQMMGR-484](https://folio-org.atlassian.net/browse/MODFQMMGR-484): Use index for simple_instance.source field
> MODFQMMGR-484: Use index for simple_instance.source field

- src/main/java/org/folio/fqm/service/FqlToSqlConverterService.java
- src/test/java/org/folio/fqm/service/FqlToSqlConverterServiceTest.java
[MODFQMMGR-466](https://folio-org.atlassian.net/browse/MODFQMMGR-466): Handle queries with dates including time component
> MODFQMMGR-466: Handle queries with dates including time component

- README.md
- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/fqm/service/CrossTenantQueryService.java
- src/main/java/org/folio/fqm/service/EntityTypeInitializationService.java
- src/main/java/org/folio/fqm/service/EntityTypeService.java
- src/main/java/org/folio/fqm/service/FqmTenantService.java
- src/test/java/org/folio/fqm/context/TestDbSetupConfiguration.java
- src/test/java/org/folio/fqm/service/CrossTenantQueryServiceTest.java
- src/test/java/org/folio/fqm/service/EntityTypeFlatteningServiceTest.java
- src/test/java/org/folio/fqm/service/EntityTypeServiceTest.java
- src/test/java/org/folio/fqm/service/FqmTenantServiceTest.java
- src/test/java/org/folio/fqm/utils/IdStreamerTest.java
This commit fixes a bug where FQM was retrieving user tenants incorrectly, resulting in it attempting to retrieve user permissions from tenants where the user may not exist
> MODFQMMGR-477 Fix bug with user-tenants API call

- src/main/resources/entity-types/inventory/composite_holdings_record.json5
- src/main/resources/entity-types/inventory/composite_item_details.json5
Reverts folio-org/mod-fqm-manager#442
> Revert "setting the flag to true"

- src/main/java/org/folio/fqm/client/SimpleHttpClient.java
- src/main/java/org/folio/fqm/repository/IdStreamer.java
- src/main/java/org/folio/fqm/service/CrossTenantQueryService.java
- src/main/java/org/folio/fqm/service/EntityTypeService.java
- src/main/java/org/folio/fqm/service/QueryManagementService.java
- src/main/java/org/folio/fqm/service/QueryProcessorService.java
- src/test/java/org/folio/fqm/service/CrossTenantQueryServiceTest.java
- src/test/java/org/folio/fqm/service/EntityTypeServiceTest.java
- src/test/java/org/folio/fqm/service/QueryManagementServiceTest.java
- src/test/java/org/folio/fqm/service/QueryProcessorServiceTest.java
[MODFQMMGR-468](https://folio-org.atlassian.net/browse/MODFQMMGR-468): Aggregate Tenant locations across all tenants
> [MODFQMMGR-468] Aggregate Tenant locations across all tenants

- src/main/resources/entity-types/circulation/composite_loan_details.json5
- src/main/resources/entity-types/circulation/simple_loan_policy.json5
[MODFQMMGR-527](https://folio-org.atlassian.net/browse/MODFQMMGR-527): Entity adjustments: simple loan policy
> [MODFQMMGR-527] Simple loan policy entity adjustments

- src/main/resources/entity-types/inventory/simple_instance.json5
- src/main/resources/entity-types/inventory/simple_item_details.json5
- src/main/resources/entity-types/orders/simple_purchase_order.json5
- src/main/resources/entity-types/orders/simple_purchase_order_line.json5
- src/main/resources/entity-types/organizations/simple_organization_types.json5
- src/main/resources/entity-types/organizations/simple_organizations.json5
- src/main/resources/entity-types/users/simple_user_details.json5
[MODFQMMGR-384](https://folio-org.atlassian.net/browse/MODFQMMGR-384):  Make array fields queryable again
> MODFQMMGR-384: Make array fields queryable again

- README.md
The much awaited PR of the season :)
> MODFQMMGR-273:adding env variable to readme

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/fqm/client/ConfigurationClient.java
- src/main/java/org/folio/fqm/resource/FqlQueryController.java
- src/main/java/org/folio/fqm/service/QueryManagementService.java
- src/main/java/org/folio/fqm/service/ResultSetService.java
- src/main/java/org/folio/fqm/utils/EntityTypeUtils.java
- src/test/java/org/folio/fqm/controller/FqlQueryControllerTest.java
- src/test/java/org/folio/fqm/service/QueryManagementServiceTest.java
- src/test/java/org/folio/fqm/service/ResultSetServiceTest.java
- src/test/java/org/folio/fqm/utils/EntityTypeUtilsTest.java
- translations/mod-fqm-manager/en_US.json
[MODFQMMGR-481](https://folio-org.atlassian.net/browse/MODFQMMGR-481): Add localize parameter to GET /query/contents endpoint
> MODFQMMGR-481: Add localize parameter to GET /query/contents endpoint

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/fqm/resource/FqlQueryController.java
- src/main/java/org/folio/fqm/service/CrossTenantQueryService.java
- src/main/java/org/folio/fqm/service/PermissionsBypassService.java
- src/main/java/org/folio/fqm/service/PermissionsRegularService.java
- src/main/java/org/folio/fqm/service/PermissionsService.java
- src/main/java/org/folio/fqm/service/QueryManagementService.java
- src/test/java/org/folio/fqm/controller/FqlQueryControllerTest.java
- src/test/java/org/folio/fqm/service/CrossTenantQueryServiceTest.java
- src/test/java/org/folio/fqm/service/PermissionsBypassServiceTest.java
- src/test/java/org/folio/fqm/service/PermissionsRegularServiceTest.java
- src/test/java/org/folio/fqm/service/QueryManagementServiceTest.java
[MODFQMMGR-563](https://folio-org.atlassian.net/browse/MODFQMMGR-563): Add /query/contents/privileged endpoint for list export
> MODFQMMGR-563: Add /query/contents/privileged endpoint for list export

- src/main/java/org/folio/fqm/client/CrossTenantClient.java
- src/main/java/org/folio/fqm/client/LanguageClient.java
- src/main/java/org/folio/fqm/config/CrossTenantFeignConfig.java
- src/main/java/org/folio/fqm/service/EntityTypeService.java
- src/test/java/org/folio/fqm/client/CrossTenantClientTest.java
- src/test/java/org/folio/fqm/service/EntityTypeServiceTest.java
[MODFQMMGR-532](https://folio-org.atlassian.net/browse/MODFQMMGR-532): Aggregate languages from all tenants in ECS environments
> MODFQMMGR-532: Aggregate languages from all tenants in ECS environments

- src/main/java/org/folio/fqm/service/EntityTypeService.java
> MODFQMMGR-566: making the api case-insensitive

- descriptors/ModuleDescriptor-template.json
> Add DB_HOST_READER env variable to module descriptor

- src/main/java/org/folio/fqm/client/CrossTenantHttpClient.java
- src/main/java/org/folio/fqm/repository/DataRefreshRepository.java
- src/main/java/org/folio/fqm/service/CrossTenantQueryService.java
- src/main/java/org/folio/fqm/service/EntityTypeService.java
- src/test/java/org/folio/fqm/service/CrossTenantQueryServiceTest.java
- src/test/java/org/folio/fqm/service/EntityTypeServiceTest.java
- src/test/java/org/folio/fqm/service/UserTenantServiceTest.java
[[MODFQMMGR-625] Aggregate dropdown values from all tenants in ECS environments](https://github.com/folio-org/mod-fqm-manager/pull/575/commits/9317836b39947cb014c319cb34a0cd6212f84e22)
> [MODFQMMGR-625] Aggregate dropdown values from all tenants in ECS environments

- src/main/resources/entity-types/inventory/simple_instance.json5
This is a missing piece from the [MODFQMMGR-617](https://folio-org.atlassian.net/browse/MODFQMMGR-617). These two flags got missed in between refactoring of the code
> MODFQMMGR-617:Convert specific arrays as JSONB to improve performance

- src/main/java/org/folio/fqm/repository/EntityTypeRepository.java
- src/main/java/org/folio/fqm/repository/ResultSetRepository.java
- src/main/java/org/folio/fqm/service/EntityTypeService.java
- src/test/java/org/folio/fqm/repository/EntityTypeRepositoryTest.java
- src/test/java/org/folio/fqm/repository/ResultSetRepositoryTest.java
- src/test/resources/entity-types/custom-fields.json5
- src/test/resources/test-db/scripts/custom-fields-source-view.sql
[MODFQMMGR-82 ](https://folio-org.atlassian.net/browse/MODFQMMGR-82): Add string-based custom fields to the Users entity type
> MODFQMMGR-82:Add string-based custom fields to the Users entity type

- src/main/java/org/folio/fqm/repository/EntityTypeRepository.java
- src/test/java/org/folio/fqm/repository/EntityTypeRepositoryTest.java
- src/test/resources/test-db/scripts/custom-fields-source-view.sql
[MODFQMMGR-376](https://folio-org.atlassian.net/browse/MODFQMMGR-376): Add textbox custom fields to the Users entity type
> MODFQMMGR-376: Add textbox custom fields to the Users entity type

- src/main/java/org/folio/fqm/service/FqlToSqlConverterService.java
- src/test/java/org/folio/fqm/service/FqlToSqlConverterServiceTest.java
[MODFQMMGR-652](https://folio-org.atlassian.net/browse/MODFQMMGR-652): Null/empty query isn't returning accurate results
> [MODFQMMGR-652] Fix null/empty queries for jsonbArrayTypes

- src/main/java/org/folio/fqm/service/EntityTypeFlatteningService.java
Nasty bug! #612 added a cache for flattened entity types, which seemed innocent enough, however, some parts of the code directly modify the returned entity types without creating a copy! This caused the original reference inside the cache to get dirtied, which would then be served to all subsequent cache hits until the key was evicted...
Most notably, this was being done in the `EntityTypeService` when removing hidden columns, meaning subsequent requests would no longer be able to use `hidden` columns, even for internal joins/filtering!
This is a quick solution (rather than hunting down every possible case and likely dealing with this again in the future (or the ideal solution of making `EntityType` etc proper data POJOs with everything `final` and that don't allow direct mutation)), …
> [MODFQMMGR-610] Clone entity types during flattening, to prevent mutation of cached ones

- src/main/resources/swagger.api/mod-fqm-manager.yaml
This crucially important PR changes the very nature of FQM itself
> Remove capitalization in include-all parameter

- src/main/java/org/folio/fqm/service/EntityTypeService.java
- src/main/resources/entity-types/inventory/simple_instance.json5
- src/main/resources/entity-types/invoice/simple_voucher_line.json5
[MODFQMMGR-511](https://folio-org.atlassian.net/browse/MODFQMMGR-511): Retrieve dropdown values for Instance - Source field
Also snuck in one small voucher_line change because I didn't want to do a separate PR
> [MODFQMMGR-511] Retrieve dropdown values for Instance - Source field

- src/main/resources/entity-types/invoice/simple_voucher.json5
One more adjustment for [MODFQMMGR-677](https://folio-org.atlassian.net/browse/MODFQMMGR-677) Entity adjustments: Vouchers
> [MODFQMMGR-677] Entity adjustments: Vouchers

- pom.xml
- translations/mod-fqm-manager/en.json
- translations/mod-fqm-manager/en_US.json
Update composite_invoice_line translation (part of [MODFQMMGR-693](https://folio-org.atlassian.net/browse/MODFQMMGR-693))
> [MODFQMMGR-693] Update composite_invoice_line translation

- src/main/java/org/folio/fqm/service/EntityTypeService.java
- src/main/java/org/folio/fqm/service/QueryManagementService.java
This project doesn't use anything that would be affected by that annotation, so it's not doing anything useful (and may have some harmful side-effects)
> MODFQMMGR-705 Remove @Transactional

- src/main/resources/entity-types/finance/composite_transaction.json5
Remove some of the sources from composite_transaction ET, as requested in [MODFQMMGR-685](https://folio-org.atlassian.net/browse/MODFQMMGR-685)
> Remove some sources from composite_transaction ET

- src/main/resources/entity-types/circulation/simple_loan.json5
[MODFQMMGR-676](https://folio-org.atlassian.net/browse/MODFQMMGR-676) : fixing hidden flag
> MODFQMMGR-676: fixing-hidden-flag

- src/main/resources/entity-types/finance/simple_transaction.json5
[MODFQMMGR-709](https://folio-org.atlassian.net/browse/MODFQMMGR-709): Fix PoLine value for Transaction - Source field
> [MODFQMMGR-709] Fix PoLine value for Transaction - Source field

- src/main/java/org/folio/fqm/service/FqlToSqlConverterService.java
- src/test/java/org/folio/fqm/service/FqlToSqlConverterServiceTest.java
Reverts folio-org/mod-fqm-manager#688
> Revert "MODFQMMGR-725:Handle Empty Strings"

- src/main/java/org/folio/fqm/repository/ResultSetRepository.java
- src/main/java/org/folio/fqm/service/ResultSetService.java
- src/main/resources/entity-types/invoice/composite_invoice__voucher_line__ledger__fund__organization.json5
- src/test/java/org/folio/fqm/repository/ResultSetRepositoryTest.java
- src/test/java/org/folio/fqm/repository/ResultSetRepositoryTestDataProvider.java
[MODFQMMGR-720](https://folio-org.atlassian.net/browse/MODFQMMGR-720): ACTUALLY fix data retrieval for ledger_fund fields
Also allow pieces of composite result_ids to be null
> [MODFQMMGR-720] Actually fix data retrieval for ledger_fund fields

- pom.xml
- src/main/java/org/folio/fqm/domain/QueryStatus.java
- src/main/java/org/folio/fqm/repository/IdStreamer.java
- src/main/java/org/folio/fqm/service/QueryExecutionService.java
- src/main/resources/db/changelog/migrations/s-migrations/changelog-s-migrations.xml
- src/test/java/org/folio/fqm/service/QueryExecutionServiceTest.java
[MODFQMMGR-723](https://folio-org.atlassian.net/browse/MODFQMMGR-723): Add MAX_SIZE_EXCEEDED query status
> [MODFQMMGR-723] Add MAX_SIZE_EXCEEDED query status

- src/main/resources/entity-types/inventory/simple_instance.json5
[MODFQMMGR-726](https://folio-org.atlassian.net/browse/MODFQMMGR-726): Fix queries for 'Instance - Cataloged date'
> [MODFQMMGR-726] Fix queries for 'Instance - Cataloged date'

- NEWS.md
> Update NEWS.md with 4.0.2 changes

- src/main/java/org/folio/fqm/service/CrossTenantQueryService.java
- src/main/java/org/folio/fqm/service/UserTenantService.java
This would be a temporary change, that will be reverted
> temp-changes

- src/main/java/org/folio/fqm/service/CrossTenantQueryService.java
- src/main/java/org/folio/fqm/service/UserTenantService.java
Reverts folio-org/mod-fqm-manager#693
> Revert "temp-changes"

- src/main/java/org/folio/fqm/service/FqlToSqlConverterService.java
- src/test/java/org/folio/fqm/service/FqlToSqlConverterServiceTest.java
[MODFQMMGR-753](https://folio-org.atlassian.net/browse/MODFQMMGR-753): Return null/empty values with 'not equal to' operator
> [MODFQMMGR-753] Return null/empty values with 'not equal to' operator

- src/main/java/org/folio/fqm/repository/EntityTypeRepository.java
- src/test/java/org/folio/fqm/repository/EntityTypeRepositoryTest.java
[MODFQMMGR-776](https://folio-org.atlassian.net/browse/MODFQMMGR-776): Introduce case-insensitivity for boolean custom fields
> [MODFQMMGR-776] Introduce case-insensitivity for boolean custom fields

- src/main/java/org/folio/fqm/service/FqlToSqlConverterService.java
- src/test/java/org/folio/fqm/service/FqlToSqlConverterServiceTest.java
[MODFQMMGR-750](https://folio-org.atlassian.net/browse/MODFQMMGR-750):  Inline certain SQL conditions to improve performance
> [MODFQMMGR-750] Inline certain SQL conditions to improve performance

- .github/workflows/test.yml
Must be in `master` to be callable :(
> Add temporary testing workflow

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/fqm/service/PermissionsRegularService.java
- src/main/resources/application.yml
- src/test/java/org/folio/fqm/IntegrationTestBase.java
- src/test/java/org/folio/fqm/service/PermissionsRegularServiceTest.java
Apparently snapshot is still running on Okapi, so we can't make FQM Eureka-only yet
This reverts commit 74b78ffb8858624f34cec11aea3f3157f3657ddc.
> MODFQMMGR-809 Restore Okapi support

- src/main/java/org/folio/fqm/repository/EntityTypeRepository.java
- src/main/java/org/folio/fqm/service/EntityTypeFlatteningService.java
- src/main/resources/entity-types/orders/purchase_order_line.json5
- src/main/resources/entity-types/orders/simple_purchase_order.json5
- src/main/resources/entity-types/users/composite_users_details.json5
- src/test/java/org/folio/fqm/repository/EntityTypeRepositoryTest.java
- src/test/java/org/folio/fqm/service/EntityTypeFlatteningServiceTest.java
- src/test/resources/entity-types/custom-fields.json5
- src/test/resources/entity-types/entity_type-02.json5
[MODFQMMGR-653](https://folio-org.atlassian.net/browse/MODFQMMGR-653) Refactor FQM's approach to custom field configuration
> [MODFQMMGR-653] Refactor FQM's approach to custom field configuration

- src/main/resources/entity-types/orders/composite_order_invoice_analytics.json5
- translations/mod-fqm-manager/en.json
[[MODFQMMGR-823] Make invoice/invoice line not required (UAT feedback)](https://folio-org.atlassian.net/browse/MODFQMMGR-823)
Add new columns to store all related fiscal years for purchase order with the ability to filter out orders that contain a certain fiscal year (e.g. current)
> [MODFQMMGR-823] Make invoice/invoice line not required (UAT feedback)

- descriptors/ModuleDescriptor-template.json
For https://folio-org.atlassian.net/browse/MODPATBLK-207
> Add mod-patron-blocks to MD

- src/main/java/org/folio/fqm/service/FqlToSqlConverterService.java
- src/test/java/org/folio/fqm/service/FqlToSqlConverterServiceTest.java
Users Address is an Array_Type
Users Departmemts is an JsonbArrayType
> Repeatable fields Equals implementation

- src/main/resources/entity-types/orders/composite_order_invoice_analytics.json5
Fix small bug from original PR for https://folio-org.atlassian.net/browse/MODFQMMGR-679
> [MODFQMMGR-679] Fix Po-User joins for 'Order - Invoice Analysis' ET

- src/main/java/org/folio/fqm/config/MigrationConfiguration.java
- src/main/java/org/folio/fqm/migration/MigrationStrategyRepository.java
- src/main/java/org/folio/fqm/migration/strategies/V13ItemLocLibraryValueChange.java
[MODFQMMGR-885](https://folio-org.atlassian.net/browse/MODFQMMGR-885): Migrate effective library fields for Items ET (Ramsons backport)
> [MODFQMMGR-885] Migrate effective library fields for Items ET (Ramsons backport)

- pom.xml
- src/main/java/org/folio/fqm/config/MigrationConfiguration.java
- src/main/java/org/folio/fqm/migration/MigrationStrategyRepository.java
- src/main/java/org/folio/fqm/migration/strategies/V13_5CustomFieldRename.java
- src/main/java/org/folio/fqm/migration/strategies/V14ItemLocLibraryValueChange.java
- src/test/java/org/folio/fqm/migration/strategies/V135CustomFieldRenameTest.java
[MODFQMMGR-884](https://folio-org.atlassian.net/browse/MODFQMMGR-884): Migrate effective library fields for Items ET
> [MODFQMMGR-884] Migrate effective library fields for Items ET (Sunflower backport)

- src/main/java/org/folio/fqm/exception/InvalidEntityTypeDefinitionException.java
- src/main/java/org/folio/fqm/service/EntityTypeInitializationService.java
- src/main/java/org/folio/fqm/service/EntityTypeService.java
- src/main/resources/entity-types/circulation/composite_loan_details.json5
- src/test/java/org/folio/fqm/context/TestDbSetupConfiguration.java
- src/test/java/org/folio/fqm/service/EntityTypeServiceTest.java
[MODFQMMGR-829](https://folio-org.atlassian.net/browse/MODFQMMGR-829): Add validation for custom ETs
Also includes some extra validation for regular ETs
> [MODFQMMGR-829] Add validation for custom ETs

- translations/mod-fqm-manager/en_US.json
> Fix translations

- translations/mod-fqm-manager/en.json
> Update voucher lines translations

- src/main/java/org/folio/fqm/utils/flattening/SourceUtils.java
[MODFQMMGR-915](https://folio-org.atlassian.net/browse/MODFQMMGR-915): Fix failing queries for "Instance - Note - Note Type"
Copy arrayTypes / objectTypes when injecting source aliases to prevent the versions belonging to entity types already in the cache from being modified
> [MODFQMMGR-915] Fix failing queries for "Instance - Note - Note Type"

- src/main/java/org/folio/fqm/config/MigrationConfiguration.java
- src/main/java/org/folio/fqm/migration/MigrationStrategyRepository.java
- src/main/java/org/folio/fqm/migration/strategies/V19RegexOperatorMigration.java
- src/test/java/org/folio/fqm/migration/strategies/V19RegexOperatorMigrationTest.java
[MODFQMMGR-614](https://folio-org.atlassian.net/browse/MODFQMMGR-614): Migrate Existing Lists with Regex Operator
> [MODFQMMGR-614] Migrate Existing Lists with Regex Operator

- src/main/java/org/folio/fqm/repository/EntityTypeRepository.java
- src/test/java/org/folio/fqm/repository/EntityTypeRepositoryTest.java
- src/test/resources/test-db/scripts/custom-fields-source-view.sql
[MODFQMMGR-590](https://folio-org.atlassian.net/browse/MODFQMMGR-590): Add support for date-based custom fields
> [MODFQMMGR-590] Add support for date-based custom fields

- src/main/resources/entity-types/srs/simple_srs_record.json5
[MODFQMMGR-924](https://folio-org.atlassian.net/browse/MODFQMMGR-924): Join SRS records on id instead of matched_id
> [MODFQMMGR-924] Join SRS records on id instead of matched_id

- src/main/java/org/folio/fqm/config/MigrationConfiguration.java
- src/main/java/org/folio/fqm/migration/MigrationStrategyRepository.java
- src/main/java/org/folio/fqm/migration/strategies/V21NotContainsAllToNeqOperatorMigration.java
- src/test/java/org/folio/fqm/migration/strategies/V21NotContainsAllToNeqOperatorMigrationTest.java
Reverts folio-org/mod-fqm-manager#922
> Revert "Revert "MODFQMMGR-901:Migrate not contains all Operator to not equals Boolean…""

- src/main/resources/entity-types/inventory/simple_holdings_record.json5
- src/main/resources/entity-types/inventory/simple_instance.json5
- src/main/resources/entity-types/inventory/simple_item.json5
[MODFQMMGR-880](https://folio-org.atlassian.net/browse/MODFQMMGR-880): Fix queries for 'Affiliation name' field
> [MODFQMMGR-880] Fix queries for 'Affiliation name' field

- src/main/resources/entity-types/inventory/simple_instance.json5
[MODFQMMGR-840](https://folio-org.atlassian.net/browse/MODFQMMGR-840) - Support query by Contributors
Fix contributor type free text search.
> MODFQMMGR-840 - Support query by Contributors

- src/main/java/org/folio/fqm/client/SettingsClient.java
- src/test/java/org/folio/fqm/client/SettingsClientTest.java
slightly tweak existing logic implemented for [MODFQMMGR-745](https://folio-org.atlassian.net/browse/MODFQMMGR-745)
> [MODFQMMGR-745] Fix tenantLocaleSettings retrieval

- src/main/resources/entity-types/users/simple_user_details.json5
[MODFQMMGR-775](https://folio-org.atlassian.net/browse/MODFQMMGR-775): Include additional user data for loans
> [MODFQMMGR-775] Include additional user data for loans
