- .github/workflows/api-doc.yml
- .github/workflows/api-lint.yml
- .github/workflows/api-schema-lint.yml
- Jenkinsfile
- src/main/resources/swagger.api/mod-fqm-manager.yaml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
> FOLIO-3678 MODFQMMGR-1 Use GitHub Workflows api-lint and api-schema-lint and api-doc

- src/main/java/org/folio/fqm/resource/PurgeQueryController.java
- src/test/java/org/folio/fqm/repository/QueryRepositoryTest.java
This commit cleans up code smells identified by Sonarqube in 2 files:
- PurgeQueryController - Unnecessary import
- QueryRepositoryTest - Usage of TimeUnit.sleep()
> MODFQMMGR-2: Clean up sonarqube code smells

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/fqm/config/BeanConfigurations.java
- src/main/java/org/folio/fqm/resource/FqlQueryController.java
- src/main/java/org/folio/fqm/service/QueryManagementService.java
- src/test/java/org/folio/fqm/controller/FqlQueryControllerTest.java
- src/test/java/org/folio/fqm/service/QueryManagementServiceTest.java
mod-list-app: Use the FQM API instead of going to its DB schema
Implementation of above ticket requires these changes in mod-fqm-manager.
> Refactor to prevent mod-lists from accessing FQM schema

- src/main/resources/db/changelog/changes/v1.0.0/entity-type-definitions.xml
- src/main/resources/db/changelog/changes/v1.0.0/harvested-views.xml
- src/main/resources/db/changelog/changes/v1.0.0/sql/derived-tables/create-view-user-details.sql
- src/main/resources/db/changelog/changes/v1.0.0/sql/entity-type-definitions/insert-item-details-definition.sql
- src/main/resources/db/changelog/changes/v1.0.0/sql/entity-type-definitions/insert-loan-details-definition.sql
- src/main/resources/db/changelog/changes/v1.0.0/sql/entity-type-definitions/insert-user-details-definition.sql
- src/main/resources/db/changelog/changes/v1.0.0/sql/entity-type-definitions/insert-users-departments-definition.sql
To enable query and reporting on user's Departments.  One user can have multiple departments they are associated with, so we need to handle the complexity of this one-to-many relationship.  
**------------------------------------------------------------------------**
NOTE: department_ids and department_names will not necessarily be in the same order. For example, the getContents API may return
```
"department_ids": ["id1", "id2],
"department_names": ["name2", "name1"]
```
> Support reporting on User's Departments

- descriptors/ModuleDescriptor-template.json
In environments that use the module descriptor for basic config, if there is no read node for the DB, the default provided in the module descriptor breaks the fallback behavior that is supposed to make FQM use the write node
> MODFQMMGR-11 Remove the _READER settings from MD

- src/main/resources/db/changelog/changes/v1.0.0/sql/create-f-unaccent-function.sql
The missing CREATE EXTENSION for unaccent is causing issues because there's no guarantee that the extension was actually set up before the create-f-unaccent-function.sql script gets run
> MODFQMMGR-12 Add CREATE EXTENSION for unaccent

- src/main/resources/db/changelog/changes/v1.0.0/sql/entity-type-definitions/insert-user-details-definition.sql
There was one disarrangement in the sorting and plus needed to remove one column.
> kjain/MODFQMMGR-17:Sort the columns

- src/main/resources/db/changelog/changes/v1.0.0/sql/entity-type-definitions/insert-user-details-definition.sql
[Hide address/department fields for User entity type](https://issues.folio.org/projects/MODFQMMGR/issues/MODFQMMGR-25)
- Temporarily remove address and department fields from User entity type definition
> MODFQMMGR-25: Hide address fields for User entity type

- descriptors/ModuleDescriptor-template.json
Add dependencies to module descriptor so that mod-fqm-manager can be deployed in snapshot
> Add dependencies to module descriptor

- descriptors/ModuleDescriptor-template.json
This commit renames the module interface name, along with the entity-types interface, to comply with established naming conventions
> MODFQMMGR-20 and MODFQMMGR-3 - Fix interface names

- src/main/resources/db/changelog/changes/v1.0.0/sql/derived-tables/create-view-item-details.sql
- src/main/resources/db/changelog/changes/v1.0.0/sql/derived-tables/create-view-user-details.sql
[Handle missing values in compound derived fields](https://issues.folio.org/browse/MODFQMMGR-26)
> MODFQMMGR-26: Handle missing values in derived fields

- src/main/resources/swagger.api/schemas/error.json
- src/main/resources/swagger.api/schemas/errors.json
- src/main/resources/swagger.api/schemas/parameters.json
[MODFQMMGR-28: Fix api-lint errors](https://issues.folio.org/browse/MODFQMMGR-28)
> MODFQMMGR-28: Fix api-lint errors

- descriptors/ModuleDescriptor-template.json
Our environment doesn't like loan-types 2.3, so downgrading to 2.2
> Downgrade loan-types interface version requirement

- src/main/resources/swagger.api/mod-fqm-manager.yaml
[MODFQMMGR-28: Fix remaining api-lint errors](https://issues.folio.org/browse/MODFQMMGR-28)
> MODFQMMGR-28: Fix remaining api-lint errors

- src/main/resources/db/changelog/changelog-master.xml
- src/main/resources/db/changelog/changes/v1.0.1/changelog-v1.0.1.xml
- src/main/resources/db/changelog/changes/v1.0.1/drv_item_details_create.xml
- src/main/resources/db/changelog/changes/v1.0.1/drv_item_holdingsrecord_instance_create.xml
[MODFQMMGR-51](https://issues.folio.org/browse/MODFQMMGR-51): queries using instance_updated_date and instance_created_date take a very long time 
Rework item views to use instance metadata indexes for faster querying
> Rework item views to use instance metadata indexes

- .gitignore
- src/main/resources/db/changelog/changelog-master.xml
- src/main/resources/db/changelog/changes/v1.0.2/changelog-v1.0.2.xml
- src/main/resources/db/changelog/changes/v1.0.2/remove_items_holdingsrecord_instance_title_searchable.xml
- src/main/resources/db/changelog/changes/v1.0.2/remove_items_instance_title_searchable.xml
- src/main/resources/db/changelog/changes/v1.0.2/update_item_details_entity_type_definition.xml
- src/main/resources/db/changelog/changes/v1.0.2/update_item_holdingsrecord_entity_type_definition.xml
`instance_title_searchable` was causing more problems than it was worth, so we removed it.
Add new Liquibase changelogs to recreate the view and update the associated entity_type_definition.
- Turns out Postgres [will not allow you to remove columns when running a `CREATE OR REPLACE VIEW` query](https://stackoverflow.com/questions/65117930/postgresql-error-cannot-drop-columns-from-view), so we have to drop it first.  We can assume it's already there, though, since previous version's changes will be created before this changelog is executed.
- ignore `.env` files
> [MODFQMMGR-72] Remove instance_title_searchable field

- src/main/java/org/folio/fqm/repository/QueryRepository.java
- src/main/java/org/folio/fqm/service/QueryManagementService.java
- src/test/java/org/folio/fqm/repository/QueryRepositoryTest.java
- src/test/java/org/folio/fqm/service/QueryManagementServiceTest.java
This commit modifies the query purge process, to make it use the query start date instead of the end date. If the server shuts down while a query is still running, the end date doesn't get set, so those queries weren't getting purged. Using the start date avoids that issue. This means that queries may get purged a little sooner (e.g., if a query takes 20 minutes to run, we'd potentially purge it 20 minutes sooner), but the threshold is long enough (3 hours and can be overridden at runtime) that this should be okay
> MODFQMMGR-73 - ***Coming this Winter*** - The Purge: Query Me This

- descriptors/ModuleDescriptor-template.json
This commit makes mod-fqm-manager provide the _tenant 2.0 interface, which will make Okapi use the POST /_/tenant API for all tenant actions
> MODFQMMGR-77 - Update the _tenant API version to 2.0

- descriptors/ModuleDescriptor-template.json
- src/main/resources/swagger.api/mod-fqm-manager.yaml
- src/test/java/org/folio/fqm/controller/MaterializedViewRefreshControllerTest.java
- Add module permissions to timers in module descriptor
- Change /materialized-views/refresh endpoint to /entity-types/materialized-views/refresh
> Fix timer permissions

- src/main/java/org/folio/fqm/repository/IdStreamer.java
- src/main/java/org/folio/fqm/repository/ResultSetRepository.java
- src/main/java/org/folio/fqm/utils/SqlFieldIdentificationUtils.java
- src/main/resources/db/changelog/changes/v1.0.4/changelog-v1.0.4.xml
- src/main/resources/db/changelog/changes/v1.0.4/update-drv-circulation-loan-status-definition.xml
- src/main/resources/db/changelog/changes/v1.0.4/update-drv-inventory-item-status-definition.xml
- src/main/resources/db/changelog/changes/v1.0.4/update-drv-item-callnumber-location-definition.xml
- src/main/resources/db/changelog/changes/v1.0.4/update-drv-item-details-definition.xml
- src/main/resources/db/changelog/changes/v1.0.4/update-drv-item-holdingsrecord-instance-definition.xml
- src/main/resources/db/changelog/changes/v1.0.4/update-drv-loan-details-definition.xml
- src/main/resources/db/changelog/changes/v1.0.4/update-drv-purchase-order-line-details-definition.xml
- src/main/resources/db/changelog/changes/v1.0.4/update-drv-user-details-definition.xml
- src/main/resources/db/changelog/changes/v1.0.4/update-src-acquisitions-unit-definition.xml
- src/main/resources/db/changelog/changes/v1.0.4/update-src-circulation-loan-policy-definition.xml
- src/main/resources/db/changelog/changes/v1.0.4/update-src-inventory-call-number-type-definition.xml
- src/main/resources/db/changelog/changes/v1.0.4/update-src-inventory-location-definition.xml
- src/main/resources/db/changelog/changes/v1.0.4/update-src-inventory-loclibrary-definition.xml
- src/main/resources/db/changelog/changes/v1.0.4/update-src-inventory-material-type-definition.xml
- src/main/resources/db/changelog/changes/v1.0.4/update-src-inventory-service-point-definition.xml
- src/main/resources/db/changelog/changes/v1.0.4/update-src-organizations-definition.xml
- src/main/resources/db/changelog/changes/v1.0.4/update-src-users-addresstypes-definition.xml
- src/main/resources/db/changelog/changes/v1.0.4/update-src-users-departments-definition.xml
- src/main/resources/db/changelog/changes/v1.0.4/update-src-users-groups-definition.xml
- src/test/java/org/folio/fqm/ModFqmManagerIT.java
- src/test/java/org/folio/fqm/repository/ResultSetRepositoryArrayTestDataProvider.java
- src/test/java/org/folio/fqm/repository/ResultSetRepositoryTestDataProvider.java
- src/test/java/org/folio/fqm/utils/IdStreamerTestDataProvider.java
- src/test/java/org/folio/fqm/utils/SqlFieldIdentificationUtilsTest.java
Build the SELECT clause from field accessors defined in the entity type. Update entity type definitions to be used with new technique.
- This ticket does not add filterValueGetters, so only valueGetters will be used initially
- For getting the filter field, filterValueGetter now takes precedence over valueGetter if both are present
- Commented out the script to create the POL entity type since it doesn't work properly right now
- Now that idValueGetter logic is implemented, we actually don't need the idView field in the entity type definitions. This field can be removed from the definition.
> MODFQMMGR-80: Build the SELECT clause from field accessors defined in the entity type

- src/main/resources/db/changelog/changes/v1.1.0/changelog-v1.1.0.xml
This improves the performance for nearly all queries that we do with that table by changing it to (query_id, result_id), since in pretty much every query, we provide a query ID and no result IDs
> MODFQMMGR-102 Rearrange the columns in the query_results PK

- src/main/java/org/folio/fqm/repository/IdStreamer.java
- src/main/java/org/folio/fqm/service/QueryExecutionCallbacks.java
- src/main/java/org/folio/fqm/service/QueryExecutionService.java
- src/main/java/org/folio/fqm/service/QueryManagementService.java
[MODFQMMGR-106](https://issues.folio.org/browse/MODFQMMGR-106): Query result count is not incrementally updated
This is a PR to fix the bug where query result counts are no longer being updated during query execution. As part of this ticket, we're also removing transactional annotations on most methods. This will allow query result counts to be updated again, without causing a dip in performance.
> MODFQMMGR-106: Remove transactions and fix query result count

- src/main/java/org/folio/fqm/service/FqlToSqlConverterService.java
- src/main/resources/db/changelog/changes/v1.1.0/update-drv-user-details-definition.xml
- src/test/java/org/folio/fqm/service/FqlToSqlConverterServiceTest.java
- translations/mod-fqm-manager/en.json
[MODFQMMGR-113: Rework array operators to avoid substring comparisons](https://issues.folio.org/projects/MODFQMMGR/issues/MODFQMMGR-113)
- This ticket supports $contains and $not_contains operators. Other operators have been discussed for use with arrays ($in, $nin), but these operators are not in the scope of this ticket
- This does not fix the POL fund distribution array column, this will be handled in another ticket
> MODFQMMGR-113: Rework array operators to avoid substring comparisons

- src/main/resources/db/changelog/changes/v1.1.0/update-drv-user-details-definition.xml
Add filterValueGetters for Users entity type
> MODFQMMGR-109: Add filterValueGetters for Users entity type

- src/main/java/org/folio/fqm/service/FqlToSqlConverterService.java
- src/test/java/org/folio/fqm/service/FqlToSqlConverterServiceTest.java
This makes it so we can configure a "valueFunction" property on a column
within an entity type, allowing us to customize how query conditions on
a column work. This way, if a filter value getter on a field changes its
behavior (e.g., removing accents), we can make the condition's value
exhibit that same behavior, to make it more intuitive to work with.
An example of this is Loan.instance_title: the filter value getter on
that field converts it to lower-case, truncates it to 600 characters,
and removes all accents. This makes it so a user could copy/paste a
title with accents from query results directly into an `instance_title
== <the title>` query and not get the expected result. With this commit,
we can do the same `lower(truncate(unaccent()))` processing on both the
field (using the …
> MODFQMMGR-116 Add support for value functions on fields

- src/main/resources/db/changelog/changes/v1.1.0/changelog-v1.1.0.xml
- src/main/resources/db/changelog/changes/v1.1.0/sql/create-mat-view-pol-payment-status.sql
- src/main/resources/db/changelog/changes/v1.1.0/sql/create-mat-view-pol-receipt-status.sql
Add unique indexes so that new materialized views can be refreshed. Also include hardcoded statuses in new views, so that they show up in the query builder even if the tenant doesn't have any records with the status.
> Add unique indexes and hardcoded statuses to new materialized views

- pom.xml
Explicitly add a version for Lombok to combat [this issue](https://stackoverflow.com/questions/77171270/compilation-error-after-upgrading-to-jdk-21-nosuchfielderror-jcimport-does-n) with JDK 21.
> Add lombok version

- pom.xml
- src/main/java/org/folio/fqm/ModFqmManagerApplication.java
- src/main/java/org/folio/fqm/client/SimpleHttpClient.java
- src/main/java/org/folio/fqm/service/EntityTypeService.java
- src/main/resources/db/changelog/changes/v1.1.0/update-drv-item-details-definition.xml
- src/test/java/org/folio/fqm/service/EntityTypeServiceTest.java
This commit makes it so we can retrieve available values for columns from configured APIs. It also expands the functionality of the column values API endpoint by making it support values coming from the entity type definition, the DB, or APIs (prior to this, it only supported the DB)
> MODFQMMGR-134 Implement support for value source APIs

- src/main/java/org/folio/fqm/service/FqlToSqlConverterService.java
- src/test/java/org/folio/fqm/service/FqlToSqlConverterServiceTest.java
Handle case insensitivity based on column datatype instead of the type of the condition value (this sounds terrible). Now, FQM can handle integer/number types even if they are sent as strings.
> Handle case insensitivity based on column datatype

- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/resources/db/changelog/changes/v1.1.0/update-drv-item-details-definition.xml
This adds the `source` property back to item_material_type in the Items entity type, so that the query builder plugin knows how to ask for the available values.
This commit also adds "inventory-storage.material-types.collection.get" to the GET /entity-types sub-permissions, so that users who can access the entity types can also access the available values for that entity type
> MODFQMMGR-134 Fix a bug with the material type config

- src/main/resources/db/changelog/changes/v1.0.0/entity-type-definitions.xml
We modified an old changeset, causing DB migrations to fail. This commit fixes that by adding a runOnChange="true" property to the changeset, so that it can run despite the modifications
> MODFQMMGR-173 Fix DB migration bug

- src/main/java/org/folio/fqm/service/FqlToSqlConverterService.java
Additional logic was added for querying fields in https://github.com/folio-org/lib-fqm-query-processor/pull/21; we want to be sure to use this logic instead of the default for resolving fields during filtration.
This logic will resolve a "base" column, enabling queries against columns with `idColumnName` without explicitly specifying the ID column in the query.
> [LIBFQMQUER-12] Use special field resolution for querying

- src/main/java/org/folio/fqm/service/FqlToSqlConverterService.java
As part of #147 , we added some logic to perform filtering on underlying ID columns, rather than the derived columns (e.g. vendor_id instead of vendor_code). This needs to be updated to also check the type of the underlying column, to ensure that we appropriately apply lowercase, date, and other conversions.
> [MODFQMMGR-180] Use proper checks for insensitive comparison

- src/main/resources/db/changelog/changes/v1.1.0/sql/entity-type-definitions/insert-holdings-definition.sql
Treat null values as false for holdings_suppress_from_discovery field, to meet the requirements of [MODFQMMGR-126](https://folio-org.atlassian.net/browse/MODFQMMGR-126) 
This is done with a filterValueGetter, so nulls will be treated as false in the WHERE clause of a query, but not in the SELECT clause (see below)
> Treat null values as false for holdings_suppress_from_discovery field

- src/main/resources/db/changelog/changes/v1.1.0/insert-instances-definition.xml
- src/main/resources/db/changelog/changes/v1.1.0/insert-organizations-contact-info-entity-type.xml
- src/main/resources/db/changelog/changes/v1.1.0/sql/entity-type-definitions/insert-holdings-definition.sql
- src/main/resources/db/changelog/changes/v1.1.0/sql/entity-type-definitions/insert-organization-definition.sql
- src/main/resources/db/changelog/changes/v1.1.0/sql/entity-type-definitions/insert-purchase-order-line-definition.sql
- src/main/resources/db/changelog/changes/v1.1.0/update-drv-item-details-definition.xml
- src/main/resources/db/changelog/changes/v1.1.0/update-drv-loan-details-definition.xml
- src/main/resources/db/changelog/changes/v1.1.0/update-drv-purchase-order-line-details-definition.xml
- src/main/resources/db/changelog/changes/v1.1.0/update-drv-user-details-definition.xml
Not all fields need to be queryable, so we introduced this flag. However, all current ones do need to be queryable, so this PR adds it to all existing fields.
Ignore the line count — I cleaned up the formatting while I was here.
> [MODFQMMGR-141] Add queryable flag

- pom.xml
- src/test/java/org/folio/fqm/ModFqmManagerApplicationTest.java
This commit bumps our dependency on Spring Boot from 3.1.2 to 3.2.3 (the latest stable release). This also bumps folio-spring-base from 7.1.2 to 8.1.0, to keep our transitive Spring dependencies in sync with our Boot version
> MODFQMMGR-186 Bump Spring Boot dependency version

- src/main/java/org/folio/fqm/service/FqlToSqlConverterService.java
- src/test/java/org/folio/fqm/service/FqlToSqlConverterServiceTest.java
[MODFQMMGR-188](https://folio-org.atlassian.net/browse/MODFQMMGR-188): fix null/empty operator for nested fields
For an array field _arrayField_ and a nested element _nestedElement_, $empty queries are handled in the following ways:
- If arrayField is not present, then 'arrayField.nestedElement IS EMPTY' returns true
-  If arrayField is an empty array, then 'arrayField.nestedElement IS EMPTY' returns true
- If arrayField is not empty, but none of the elements contain nestedElement, then 'arrayField.nestedElement IS EMPTY' returns true
- If arrayField is not empty, and any of the elements contain nestedElement, then 'arrayField.nestedElement IS EMPTY' returns false
> MODFQMMGR-188: fix null/empty operator for nested fields

- README.md
- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/fqm/config/FqmConfiguration.java
- src/main/java/org/folio/fqm/exception/MaxQuerySizeExceededException.java
- src/main/java/org/folio/fqm/exceptionhandler/FqmExceptionHandler.java
- src/main/java/org/folio/fqm/service/DataBatchCallback.java
- src/main/java/org/folio/fqm/service/QueryExecutionCallbacks.java
- src/main/java/org/folio/fqm/service/QueryExecutionService.java
- src/main/java/org/folio/fqm/service/QueryManagementService.java
- src/main/resources/application.yml
- src/test/java/org/folio/fqm/service/DataBatchCallbackTest.java
- src/test/java/org/folio/fqm/service/QueryExecutionCallbacksTest.java
- src/test/java/org/folio/fqm/service/QueryExecutionServiceTest.java
- src/test/java/org/folio/fqm/service/QueryManagementServiceTest.java
[MODFQMMGR-172](https://folio-org.atlassian.net/browse/MODFQMMGR-172): Set a limit on the maximum number of query results
- Define a variable max-query-size in application.yml. This is the application-wide maximum query size
- Define a variable in SubmitQuery requests called maxSize. This is the maximum query size for an individual query.
- If SubmitQuery doesn't contain a maxSize field, use the application-wide max query size. If SubmitQuery does contain a maxSize field, use min(application-wide-max-query-size, individual-query-max-query-size) as the maximum size.
- If maximum size is exceeded, throw MaxQuerySizeExceededException
> MODFQMMGR-172: Set a limit on the maximum number of query results

- src/main/java/org/folio/fqm/client/SimpleHttpClient.java
- src/main/java/org/folio/fqm/service/EntityTypeService.java
- src/test/java/org/folio/fqm/service/EntityTypeServiceTest.java
This commit adds a "limit" query parameter with a value of 1000 to every value source API call, since some API endpoints have a fairly low default limit. This brings the API approach to source values in line with the DB approach (which also limits to 1000). In the future, we may need to make this more flexible, in case we run into API endpoints in FOLIO that reject this query parameter
> MODFQMMGR-201 Add limit param to value source API calls

- src/main/resources/db/changelog/changes/v1.1.0/insert-instances-definition.xml
In cases where an instance's mode of issuance is null, the whole instance disappears from the Instances entity type. This commit addresses that bug by changing the join between instances and mode of issuance from an inner join to a left join
> MODFQMMGR-208 Change a JOIN to a LEFT JOIN

- src/main/java/org/folio/fqm/repository/MaterializedViewRefreshRepository.java
- src/main/java/org/folio/fqm/service/FqmTenantService.java
- src/main/resources/db/changelog/changes/v1.1.0/changelog-v1.1.0.xml
- src/main/resources/db/changelog/changes/v1.1.0/sql/create-mat-view-drv-inventory-statistical-code-full.sql
- src/main/resources/db/changelog/changes/v1.1.0/sql/create-mat-view-languages.sql
- src/main/resources/db/changelog/changes/v1.1.0/sql/create-mat-view-pol-payment-status.sql
- src/main/resources/db/changelog/changes/v1.1.0/sql/create-mat-view-pol-receipt-status.sql
The second run will run a special "slow" context in a separate thread,
so that FQM can continue bootstrapping its DB without holding up other
modules
> MODFQMMGR-210 Split DB migrations into a fast synchronous stage and a slow asynchronous stage

- descriptors/ModuleDescriptor-template.json
This change should allow FQM to work with Orchid and Poppy versions of contributor-name-types
> MODFQMMGR-217 Lower contributor-name-types dependency version

- src/main/java/org/folio/fqm/repository/EntityTypeRepository.java
- src/test/java/org/folio/fqm/repository/EntityTypeRepositoryTest.java
> MODFQMMGR-289:custom fields not available when building queries

- src/main/resources/entity-types/inventory/drv_instances.json5
[MODFQMMGR-290: Fix instance_status join condition](https://folio-org.atlassian.net/browse/MODFQMMGR-290)
Make instance_status join a LEFT JOIN so that instance info is maintained even if statusId is null.
> MODFQMMGR-290: Fix instance_status join condition

- src/test/java/org/folio/fqm/context/ReadWriteSplitTest.java
- src/test/java/org/folio/fqm/context/ReadWriteSplitTestConfiguration.java
[MODFQMMGR-221: Create test to verify read-write split is functioning properly](https://folio-org.atlassian.net/browse/MODFQMMGR-221)
Create a ReadWriteSplitTestConfiguration class to create required beans with mock datasources. Have spring inject the beans into a repository class. Perform read/write operations and check that the correct datasource is used.
>  MODFQMMGR-221: Create test to verify read-write split is functioning properly

- descriptors/ModuleDescriptor-template.json
- src/main/resources/entity-types/organizations/drv_organization_contacts.json5
- src/main/resources/entity-types/organizations/drv_organization_details.json5
- src/main/resources/entity-types/pol/drv_purchase_order_line_details.json5
- src/test/java/org/folio/fqm/IntegrationTestBase.java
Remove subpermissions from the fqm.entityTypes.item.get. Move the permissions to the entity type definitions.
Every permission removed from the MD is now contained within the definitions of any entity types that need it. 2 permissions were removed completely:
`acquisitions-units-storage.memberships.collection.get`
`acquisitions-units-storage.units.collection.get`
These are unneeded, because access to acquisitions units is obtained through `acquisitions-units.units.collection.get`
> Remove subpermissions from fqm.entityTypes.item.get permission set

- descriptors/ModuleDescriptor-template.json
We use permissions provided by mod-orders, mod-organizations, and mod-circulation, but don't have any interfaces from those modules in our module descriptor. This is a PR to add the missing interfaces.
> Add required interfaces to module descriptor

- descriptors/ModuleDescriptor-template.json
[MODFQMMGR-303](https://folio-org.atlassian.net/browse/MODFQMMGR-303): holdings-storage API version update
The version update introduces a breaking change, making one new field required in the holdings schema. This shouldn't affect mod-fqm-manager in any way though.
> MODFQMMGR-303: Add additional holdings-storage version to module descriptor

- src/main/java/org/folio/fqm/repository/EntityTypeRepository.java
- src/main/java/org/folio/fqm/resource/EntityTypeController.java
- src/main/java/org/folio/fqm/service/EntityTypeService.java
- src/main/resources/swagger.api/mod-fqm-manager.yaml
- src/main/resources/swagger.api/schemas/EntityTypeSummaryDTO.json
- src/test/java/org/folio/fqm/controller/EntityTypeControllerTest.java
- src/test/java/org/folio/fqm/repository/EntityTypeRepositoryTest.java
- src/test/java/org/folio/fqm/service/EntityTypeServiceTest.java
> [MODFQMMGR-333] Expose endpoint to fetch entity types with missing permissions

- src/main/java/org/folio/fqm/model/FqlQueryWithContext.java
- src/main/java/org/folio/fqm/repository/IdStreamer.java
- src/main/java/org/folio/fqm/service/QueryExecutionService.java
- src/main/java/org/folio/fqm/service/QueryManagementService.java
- src/main/java/org/folio/fqm/service/QueryProcessorService.java
- src/test/java/org/folio/fqm/service/QueryExecutionServiceTest.java
- src/test/java/org/folio/fqm/service/QueryManagementServiceTest.java
- src/test/java/org/folio/fqm/service/QueryProcessorServiceTest.java
- src/test/java/org/folio/fqm/utils/IdStreamerTest.java
The localization service uses information from the current thread to determine which locale(s) should be used; this normally works fine, however, Spring discards this information when we are processing queries asynchronously, causing a large quantity of logged errors. This does not affect the results (since the translated names are not used for query processing), however, it is annoying to look at.
It [is possible to share context](https://stackoverflow.com/a/50138897/4236490) with async threads in Spring, however, just doing this alone causes weirder issues where Tomcat will discard the request context once the request completes, causing it to no longer be accessible when the async thread attempts to access it — I was unable to find any way around this without disabling request recycling …
> [MODFQMMGR-387] Pre-resolve locale-related information before starting async tasks

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/fqm/service/EntityTypeInitializationService.java
- src/main/resources/entity-types/inventory/simple_instance.json5
- src/test/java/org/folio/fqm/context/TestDbSetupConfiguration.java
[MODFQMMGR-339: Extend entity type response to add additional data column for query builder](https://folio-org.atlassian.net/browse/MODFQMMGR-339)
This story makes the new ECS columns available for use from the query builder.
> MODFQMMGR-339: Include ECS columns in query builder

- src/main/java/org/folio/fqm/repository/IdStreamer.java
- src/main/java/org/folio/fqm/repository/ResultSetRepository.java
- src/main/resources/entity-types/users/simple_user_details.json5
We had some effectively dead code that was causing us to render the WHERE clause of converted FQL queries without the jOOQ context that normally tells it to render for PostgreSQL. The contains_all operator depends on jOOQ's special handling for PostgreSQL, so rendering without the right context was breaking the operator
This commit removes that code, so that the WHERE clause is rendered with the correct context
> MODFQMMGR-373 Fix bug with contains_all

- src/main/resources/entity-types/inventory/simple_instance.json5
- src/main/resources/entity-types/inventory/simple_inventory_statistical_code_full.json5
- translations/mod-fqm-manager/en.json
> MODFQMMGR-311 Fix instance stat codes

- src/main/resources/entity-types/finance/composite_ledger__fund.json5
- src/main/resources/entity-types/inventory/composite_instances.json5
- src/main/resources/entity-types/invoice/composite_invoice__voucher_line__fund_distribution.json5
- src/main/resources/entity-types/invoice/composite_invoice__voucher_line__ledger_fund__organization.json5
- src/main/resources/entity-types/invoice/composite_invoice__voucher_line__organization.json5
- src/main/resources/entity-types/invoice/composite_voucher_line__fund_distribution.json5
- src/main/resources/entity-types/invoice/composite_voucher_line__voucher__ledger_fund.json5
- src/main/resources/entity-types/users/composite_users_details.json5
This fixes issues with `defaultSort` causing queries to fail.
I can confirm this fixes the issue for instances and user details. The finance entity types have further issues outside the scope of this fix.
> [MODFQMMGR-419] Fix column values for several entity types

- src/main/resources/entity-types/inventory/simple_instance.json5
This is a temporary change, to ensure the tenant ID is available as part of the ID, even in non-ECS environments. After consumers have switched away from the `.../sortedIds` endpoint, so that they can retrieve the tenant ID more directly via query results, we can switch this back to ECS-only.
> MODFQMMGR-421 Make instance tenant_id not be ECS-only

- README.md
- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/fqm/repository/EntityTypeRepository.java
- src/main/resources/application.yml
- src/test/java/org/folio/fqm/IntegrationTestBase.java
- src/test/java/org/folio/fqm/utils/IdStreamerTest.java
- src/test/java/org/folio/fqm/utils/IdStreamerTestDataProvider.java
- src/test/resources/application-test.yml
This commit adds a new cache for entity types to EntityTypeRepository, to cut down on repeated loads of entity types. The default cache duration is 1 hour, but this can be overridden via system property. Additionally, the value in the module descriptor is set to 5 minutes, in order to strike more of a balance between performance and practicality in dev environments (although devs should consider reducing this further when actively creating/updating entity type definitions)
If you are changing/removing …
> MODFQMMGR-415 Add an entity type defintion cache

- src/main/java/org/folio/fqm/resource/EntityTypeController.java
- src/main/java/org/folio/fqm/service/EntityTypeService.java
- src/main/java/org/folio/fqm/service/QueryManagementService.java
- src/test/java/org/folio/fqm/controller/EntityTypeControllerTest.java
- src/test/java/org/folio/fqm/service/EntityTypeServiceTest.java
- src/test/java/org/folio/fqm/service/QueryManagementServiceTest.java
Add sortColumns parameter to getEntityTypeDefinition method. sortColumns=true will be used only by the EntityTypeController's getEntityTypeDefinition method. Otherwise it'll be false. This will allow the /entity-type/{entity-type-id} API to sort columns according to their translations, while ensuring columns stay unsorted behind the scenes (so that query results are saved in a consistent manner)
> Add sortColumns parameter to getEntityTypeDefinition method

- src/main/java/org/folio/fqm/service/EntityTypeService.java
With a recent change, the source property on columns started taking precedence over valueSourceApi, but source is required on columns that use valueSourceApi, making it effectively break all valueSourceApi columns. This commit rearranges taht code, so that valueSourceApi (and values, which is more of an edge case, but has the same bug) has a higher precedence
> MODFQMMGR-448 Fix bug with valueSourceApi

- src/main/resources/entity-types/inventory/simple_holdings_records.json5
- src/main/resources/entity-types/inventory/simple_instance.json5
- src/main/resources/entity-types/inventory/simple_item_details.json5
> MODFQMMGR-480 Make tenant_id fields ECS-only

- src/main/java/org/folio/fqm/service/CrossTenantQueryService.java
- src/main/java/org/folio/fqm/service/EntityTypeFlatteningService.java
- src/main/java/org/folio/fqm/service/EntityTypeService.java
- src/main/java/org/folio/fqm/service/UserTenantService.java
- src/main/resources/application.yml
- src/main/resources/swagger.api/schemas/EntityTypeSummary.json
- src/test/java/org/folio/fqm/service/CrossTenantQueryServiceTest.java
- src/test/java/org/folio/fqm/service/EntityTypeFlatteningServiceTest.java
- src/test/java/org/folio/fqm/service/EntityTypeServiceTest.java
- src/test/java/org/folio/fqm/service/UserTenantServiceTest.java
- src/test/java/org/folio/fqm/utils/IdStreamerTest.java
- src/test/java/org/folio/fqm/utils/IdStreamerTestDataProvider.java
[MODFQMMGR-456](https://folio-org.atlassian.net/browse/MODFQMMGR-456): Check whether entity type is cross-tenant when retrieving definition
> MODFQMMGR-456: Check whether entity type is cross-tenant when retrieving definition

- src/main/java/org/folio/fqm/service/EntityTypeService.java
- src/test/java/org/folio/fqm/service/EntityTypeServiceTest.java
Add check for ECS when getting entity type summaries (to allow for hiding lists on landing page)
> Check whether ECS is enabled when getting entity type summaries

- src/main/resources/entity-types/inventory/simple_item_details.json5
This field's value getter points at the wrong datapoint, so this commit corrects that
> MODFQMMGR-500 Fix item temp loan type ID

- README.md
- src/main/java/org/folio/fqm/config/PermissionsConfiguration.java
Per meeting with Sobha and friends, one of the main concerns was that a new member of the DevOps team could see the permission bypass env variable in the README and accidentally use it.
This moves this env variable to its own section, with a scary warning.
> [MODFQMMGR-453] Make local-only env variables look scarier

- src/main/java/org/folio/fqm/client/SimpleHttpClient.java
- src/main/java/org/folio/fqm/service/EntityTypeService.java
- src/test/java/org/folio/fqm/service/EntityTypeServiceTest.java
Mod-search doesn't like our feign client sending the okapi tenant in the request (works fine for other APIs). Removing it for now to get things mostly working for languages.
> Don't aggregate languages across tenants

- src/main/resources/entity-types/circulation/composite_loan_details.json5
- src/main/resources/entity-types/inventory/composite_holdings_record.json5
- src/main/resources/entity-types/inventory/composite_item_details.json5
- src/main/resources/entity-types/orders/composite_purchase_order_lines.json5
- src/main/resources/entity-types/organizations/simple_organizations.json5
This commit fixes the defaultSort property in these entity types into fully qualified column references, to fix an issue where these entity types just didn't work with the synchronous query endpoint
> MODFQMMGR-538 Fix defaultSort in composite ETs

- descriptors/ModuleDescriptor-template.json
We don't actually need 5.8, and it's making life difficuly, so let's just use 5.7 ¯\_(ツ)_/¯
> MODFQMMGR-570 Downgrade the permissions MD dependency to 5.7

- src/main/java/org/folio/fqm/client/ConfigurationClient.java
- src/main/java/org/folio/fqm/client/ConfigurationClientRaw.java
- src/main/java/org/folio/fqm/service/ResultSetService.java
- src/test/java/org/folio/fqm/client/ConfigurationClientTest.java
- src/test/java/org/folio/fqm/service/ResultSetServiceTest.java
The backend was using the current date to determine the UTC offset, which resulted in either four or five hours (in America/New_York), depending on the date that the server handled the request. This could cause some discrepancies and for queries to return different values when entering/leaving daylight savings/summer time.
> [MODFQMMGR-573] Consider converted date for timezone offsets, rather than system time

- descriptors/ModuleDescriptor-template.json
This commit sets the DB_HOST_READER to "" in the module descriptor, so that the env var is still listed there, but we still maintain the defauly reader fallback behavior when someone uses the values from the MD
> Set DB_HOST_READER to "" in the MD

- README.md
- descriptors/ModuleDescriptor-template.json
This commit fixes a typo in the
"mod-fqm-manager.entity-type-cache-timeout-seconds" config setting. It also updates the README to reflect the new default value for this setting
> MODFQMMGR-577 Fix typo in MD and updated README

- src/main/java/org/folio/fqm/repository/IdStreamer.java
When a DB is under heavy load, we seem to be trying to retrieve the query before it's had a chance to be saved to the DB. Delay running the query cancellation check for 30s to give time for the query to be saved.
> Delay query cancellation monitor for 30 seconds

- descriptors/ModuleDescriptor-template.json
- src/main/resources/application.yml
If we have 12 application threads, we need a hikari pool size of 12 too.
Also fix module descriptor
> Set Hikari max pool size to 12

- src/main/resources/entity-types/inventory/simple_instance.json5
The error in `Loan policy — Name` traced back to the instance `format_names` field, where an unqualified `:sourceAlias` resulted in postgres attempting to find the table `null`:
```
select "loans.loan".id as "loans.id", "loans.loan".creation_date as "loans.created_at", "loans.loan".jsonb->>'userId' as "loans.user_id", "loans.loan".jsonb->>'proxyUserId' as "loans.proxy_user_id", "loans.loan".jsonb->>'itemId' as "loans.item_id", "loans.loan".jsonb->'status'->>'name' as "loans.status_name", "loans.loan".jsonb->>'loanDate' as "loans.checkout_date", "loans.loan".jsonb->>'dueDate' as "loans.due_date", "loans.loan".jsonb->>'returnDate' as "loans.return_date", "loans.loan".jsonb->>'action' as "loans.action", "loans.loan".jsonb->>'itemStatus' as "loans.item_status", …
```
> [MODFQMMGR-623] Resolve query failures against loan policy field

- src/main/java/org/folio/fqm/client/OrganizationsClient.java
- src/main/java/org/folio/fqm/migration/MigrationStrategyRepository.java
- src/main/java/org/folio/fqm/migration/strategies/V11OrganizationNameCodeOperatorChange.java
- src/main/resources/entity-types/organizations/simple_organizations.json5
- src/test/java/org/folio/fqm/migration/strategies/V11OrganizationCodeOperatorChangeTest.java
- translations/mod-fqm-manager/en.json
- Restores `id` field for querying (by creating a new `_id` to use for `idColumnName`s, instead)
- Handles migration of `name` field similar to `code`
> [MODFQMMGR-618] Organizations migration id/name/code fixes

- src/main/java/org/folio/fqm/exceptionhandler/FqmExceptionHandler.java
This commit adds a handler for unhandled exceptions and adds their stacktrace to the returned HTTP response. This makes it so we can differentiate different HTTP 500 responses returned from the back end
> MODFQMMGR-630 Add generic exception handler

- src/main/java/org/folio/fqm/config/MigrationConfiguration.java
- src/main/java/org/folio/fqm/migration/MigrationStrategyRepository.java
- src/main/java/org/folio/fqm/migration/strategies/V13CustomFieldRename.java
- src/main/java/org/folio/fqm/repository/EntityTypeRepository.java
- src/test/java/org/folio/fqm/IntegrationTestBase.java
- src/test/java/org/folio/fqm/migration/MigrationStrategyRepositoryTest.java
- src/test/java/org/folio/fqm/migration/strategies/V13CustomFieldRenameTest.java
- src/test/java/org/folio/fqm/repository/EntityTypeRepositoryTest.java
[MODFQMMGR-642](https://folio-org.atlassian.net/browse/MODFQMMGR-642): Use custom field UUIDs for BE custom field names. This will make it possible to track changes to custom field names 
+  Add migration script for updated custom field names
> [MODFQMMGR-642] Use custom field UUIDs for BE custom field names

- src/main/resources/entity-types/invoice/composite_voucher_line_totals_per_account.json5
This commit updates the composite_voucher_line_totals_per_account entity type's fields, to make the ET actually usable
> MODFQMMGR-649 Mark ET fields as queryable and visibleByDefault

- src/main/java/org/folio/fqm/service/EntityTypeFlatteningService.java
- src/main/java/org/folio/fqm/service/LocalizationService.java
- src/main/java/org/folio/fqm/utils/flattening/SourceUtils.java
- src/test/java/org/folio/fqm/service/EntityTypeFlatteningServiceTest.java
- src/test/java/org/folio/fqm/service/LocalizationServiceTest.java
- src/test/java/org/folio/fqm/utils/flattening/SourceUtilsCopyTest.java
This change makes it so all columns are sorted in a group within whatever entity type they are defined in. This way, columns within simples are always sorted (vs before, when they were only sorted when imported into a composite), and any columns defined directly in a composite are also sorted as a group that appears before any imported columns
> MODFQMMGR-543 Refactor column sorting within ET sources

- src/main/resources/entity-types/inventory/simple_contributor_name_type.json5
Fix a bug I noticed in simple_contributor_name_type when testing the /entity-types?includeAll param for edge-fqm
> Fix contributor_name_type ET

- Dockerfile
- Jenkinsfile
- pom.xml
- src/main/java/org/folio/fqm/config/PermissionsConfiguration.java
- src/test/java/org/folio/fqm/context/DatasourceConnectionTest.java
- src/test/java/org/folio/fqm/context/TestcontainerBeanFactoryPostProcessor.java
- src/test/java/org/folio/fqm/controller/DataRefreshControllerTest.java
- src/test/java/org/folio/fqm/controller/EntityTypeControllerTest.java
- src/test/java/org/folio/fqm/controller/FqlQueryControllerTest.java
- src/test/java/org/folio/fqm/controller/MigrationControllerTest.java
- src/test/java/org/folio/fqm/controller/PurgeQueryControllerTest.java
- src/test/resources/application-test.yml
This commit bumps the module from Java 17 to 21. It also updates to dependencies that are compatible with this upgrade and makes a few small test and config changes to account for these dependeny upgrades. Finally, it upgrades a few integration tests to use PostgreSQL 16 instead of 12 (this is unreleated to the Java upgrade, but is still important)
> FOLIO-4237 Upgrade to Java 21

- src/main/java/org/folio/fqm/aspect/EntityTypePermissionsAspect.java
- src/main/java/org/folio/fqm/repository/EntityTypeRepository.java
- src/main/java/org/folio/fqm/repository/ResultSetRepository.java
- src/main/java/org/folio/fqm/service/EntityTypeFlatteningService.java
- src/main/java/org/folio/fqm/service/EntityTypeService.java
- src/main/java/org/folio/fqm/service/PermissionsRegularService.java
- src/main/java/org/folio/fqm/service/ResultSetService.java
- src/test/java/org/folio/fqm/aspect/EntityTypePermissionsAspectTest.java
- src/test/java/org/folio/fqm/service/EntityTypeFlatteningServiceTest.java
- src/test/java/org/folio/fqm/service/EntityTypeServiceTest.java
- src/test/java/org/folio/fqm/service/FqlToSqlConverterServiceIT.java
- src/test/java/org/folio/fqm/service/PermissionsRegularServiceTest.java
- src/test/java/org/folio/fqm/service/ResultSetServiceTest.java
[MODFQMMGR-695](https://folio-org.atlassian.net/browse/MODFQMMGR-695): Fix entity type cache bug in ECS environments
The core of this fix is to never allow EntityTypeCacheKey's tenantId to be null
> [MODFQMMGR-695] Fix entity type cache bug in ECS environments

- src/main/java/org/folio/fqm/utils/EntityTypeUtils.java
- src/test/java/org/folio/fqm/utils/EntityTypeUtilsTest.java
[MODFQMMGR-728](https://folio-org.atlassian.net/browse/MODFQMMGR-728) Ensure tenant_id column is last component of result_id
Now that we're ordering ET columns by their localized names, there's a chance that the `tenant_id` field can come before the rest of the result_id (e.g. instance_id for instances, holdings_id for holdings, etc.). While this is fine for FQM and lists, this breaks bulk-edit, because it assumes that the tenant_id will always come last in the response from the `/sortedIds` endpoint. In practice, the only ET that this actually affected was Holdings, because tenant_id naturally comes last for the other ETs when ordering columns alphabetically (in English, at least). 
This PR introduces a kind of silly feeling change: now when we get the result ids for an ET, we do a quick …
> [MODFQMMGR-728] Ensure tenant_id column is last component of result_id

- src/main/resources/entity-types/inventory/simple_item.json5
[MODFQMMGR-758](https://folio-org.atlassian.net/browse/MODFQMMGR-758): Make 'Item - Former IDs' field non-queryable
> [MODFQMMGR-758] Make 'Item - Former IDs' field non-queryable

- descriptors/ModuleDescriptor-template.json
[MODORDERS-1269](https://folio-org.atlassian.net/browse/MODORDERS-1269) - Remove alerts and reporting codes from order lines, use a single order line schema
Updated orders interface version
[Related PRs](https://github.com/folio-org/mod-orders-storage/pull/477)
> [MODORDERS-1269] Updated orders interface version

- README.md
- pom.xml
- src/main/java/org/folio/fqm/repository/IdStreamer.java
- src/main/java/org/folio/fqm/repository/QueryRepository.java
- src/main/java/org/folio/fqm/service/QueryManagementService.java
- src/main/java/org/folio/fqm/service/QueryProcessorService.java
- src/main/resources/application.yml
- src/test/java/org/folio/fqm/repository/IdStreamerTest.java
- src/test/java/org/folio/fqm/repository/QueryRepositoryTest.java
- src/test/java/org/folio/fqm/service/QueryManagementServiceTest.java
- src/test/java/org/folio/fqm/service/QueryProcessorServiceTest.java
- src/test/resources/application-test.yml
This PR is to handle situations where a query is still marked as in-progress when it's not actually running, due to something like a server crash.
When retrieving the FQM query details, if the query is in the in-progress status, it will check running queries in the DB to find the corresponding DB query. If it's not found, it re-checks the FQM query status. If the query is still marked as in-progress, then FQM will update its status to failed, then return the failed query details.
> MODFQMMGR-518 Handle zombie queries 🧟

- README.md
- descriptors/ModuleDescriptor-template.json
[MODFQMMGR-781](https://folio-org.atlassian.net/browse/MODFQMMGR-781): Use QUERY_RETENTION_DURATION env variable
> [MODFQMMGR-781] Update documentation with correct query retention variable name

- src/main/resources/entity-types/invoice/composite_invoice_line_fund_distribution.json5
- translations/mod-fqm-manager/en.json
[[MODFQMMGR-752] Add "Fund distribution value" column to "composite_invoice_line_fund_distribution"](https://folio-org.atlassian.net/browse/MODFQMMGR-752)
Add new columns for displaying fund distribution value and amount
> [MODFQMMGR-752] Add fund distribution value and amount columns

- src/main/java/org/folio/fqm/service/FqlToSqlConverterService.java
- src/test/java/org/folio/fqm/service/FqlToSqlConverterServiceTest.java
[MODFQMMGR-754](https://folio-org.atlassian.net/browse/MODFQMMGR-754): Return null/empty values with 'not in' operator
> [MODFQMMGR-754] Return null/empty values with 'not in' operator

- src/main/java/org/folio/fqm/exception/InvalidEntityTypeDefinitionException.java
- src/main/java/org/folio/fqm/repository/EntityTypeRepository.java
- src/test/java/org/folio/fqm/repository/EntityTypeRepositoryTest.java
This check happens immediately after loading and parsing the ET, to ensure the ID is a valid UUID, as in invalid ID will cause issues later on
> MODFQMMGR-827 Add ET ID check when loading ETs

- src/main/java/org/folio/fqm/service/FqlToSqlConverterService.java
- src/test/java/org/folio/fqm/service/FqlToSqlConverterServiceTest.java
[MODFQMMGR-867](https://folio-org.atlassian.net/browse/MODFQMMGR-867) - Repeatable fields "contains" implementation
Implemented handleRegEx logic for arrays and jsonb arrays
> MODFQMMGR-867 - Repeatable fields "contains" implementation

- src/main/java/org/folio/fqm/config/MigrationConfiguration.java
- src/main/java/org/folio/fqm/migration/MigrationStrategyRepository.java
- src/main/java/org/folio/fqm/migration/strategies/AbstractLibraryValueChangeMigration.java
- src/main/java/org/folio/fqm/migration/strategies/V13CustomFieldRename.java
- src/main/java/org/folio/fqm/migration/strategies/V14ItemLocLibraryValueChange.java
- src/main/java/org/folio/fqm/migration/strategies/V15AlertsAndReportingCodesRemoval.java
- src/main/java/org/folio/fqm/migration/strategies/V16OrganizationSimpleToCompositeMigration.java
- src/main/java/org/folio/fqm/migration/strategies/V9LocLibraryValueChange.java
- src/test/java/org/folio/fqm/migration/strategies/V6V7V8V9V14ValueChangeConsolidatedTest.java
[MODFQMMGR-883](https://folio-org.atlassian.net/browse/MODFQMMGR-883) Migrate "Effective library - Name" and "Effective library - Code" fields for Items ET
As of right now, the latest migration on Ramsons is V12 (meaning queries end up as version 13) and the latest migration on Sunflower is V13 (meaning queries end up as version 14).
- The original V14 and V15 (present only in Trillium and later) get incremented by one each, so V14 becomes V15 and V15 becomes V16
- This new migration (call it bugfix-migration) is inserted as V14 in Sunflower and Trillium
- bugfix-migration is inserted as V13 in Ramsons and upgrades queries to version 13.5
- In Sunflower and Trillium, the original V13 becomes V13.5 and is modified to accept queries with version 13.5
- Tenants on Ramsons: tenant will …
> [MODFQMMGR-883] Migrate effective library fields for Items ET

- src/main/java/org/folio/fqm/service/QueryManagementService.java
- src/test/java/org/folio/fqm/service/QueryManagementServiceTest.java
NOTE: unlike the async query, which returns the total number of records matching the query, the synchronous query
API returns the number of records included in this individual response, which may be less than the total number of records matching the query.
> Add total record count to synchronous query API

- src/main/resources/entity-types/inventory/composite_item_details.json5
- translations/mod-fqm-manager/en.json
[MODFQMMGR-907](https://folio-org.atlassian.net/browse/MODFQMMGR-907) - Composite item extension to support "holding_permanent_location.name" field
It is necessary for Bulk Operations to include the field "holding_permanent_location.name" in the composite item schema. 
Adding new field in composite item schema.
> MODFQMMGR-907 - Composite item extension to support "holding_permanent_location.name" field

- descriptors/ModuleDescriptor-template.json
Add back config 2.0 to mod-fqm-manager's module descriptor. I removed it prematurely, since it's still necessary until [MODFQMMGR-746](https://folio-org.atlassian.net/browse/MODFQMMGR-746) is completed
> Temporarily add back config interface to module descriptor
